create table if not exists public.places (id text primary key, data jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.idols (id text primary key, data jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.works (id text primary key, data jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.cities (id text primary key, data jsonb not null, updated_at timestamptz not null default now());
alter table public.places enable row level security;
alter table public.idols enable row level security;
alter table public.works enable row level security;
alter table public.cities enable row level security;
drop policy if exists "public read places" on public.places;
drop policy if exists "public content insert places" on public.places;
drop policy if exists "public content update places" on public.places;
create policy "public read places" on public.places for select to anon using (true);
create policy "public content insert places" on public.places for insert to anon with check (true);
create policy "public content update places" on public.places for update to anon using (true) with check (true);
drop policy if exists "public read idols" on public.idols;
drop policy if exists "public content insert idols" on public.idols;
drop policy if exists "public content update idols" on public.idols;
create policy "public read idols" on public.idols for select to anon using (true);
create policy "public content insert idols" on public.idols for insert to anon with check (true);
create policy "public content update idols" on public.idols for update to anon using (true) with check (true);
drop policy if exists "public read works" on public.works;
drop policy if exists "public content insert works" on public.works;
drop policy if exists "public content update works" on public.works;
create policy "public read works" on public.works for select to anon using (true);
create policy "public content insert works" on public.works for insert to anon with check (true);
create policy "public content update works" on public.works for update to anon using (true) with check (true);
drop policy if exists "public read cities" on public.cities;
drop policy if exists "public content insert cities" on public.cities;
drop policy if exists "public content update cities" on public.cities;
create policy "public read cities" on public.cities for select to anon using (true);
create policy "public content insert cities" on public.cities for insert to anon with check (true);
create policy "public content update cities" on public.cities for update to anon using (true) with check (true);
