import {ArrowLeft,Building2,Check,Edit3,ExternalLink,FileCheck2,LayoutDashboard,LogOut,MapPin,MessageSquareText,Plus,Search,Sparkles,Trash2,UploadCloud,X} from 'lucide-react'
import {FormEvent,useState} from 'react'
import {Link,useLocation,useNavigate,useSearchParams} from 'react-router-dom'
import {extractPlaceFromText,type ExtractedPlaceData} from '../services/aiExtractor'
import {recalculateBasicCounts,useAdminStore,useBasicDataStore,useFeedbackStore} from '../stores'
import type {AdminPlace} from '../stores'
import type {Credibility} from '../types'
import {getEvents,replaceEvents,type XunjiEvent} from '../services/analytics'
import {useAdminAuth} from '../components/AdminAuth'
import {importBackupToCloud,parseXunjiBackup,type BackupImportResult} from '../services/backup'
import {ImageUploadControl} from '../components/ImageUploadControl'

const relationNames:Record<string,string>={same_style:'同款',filming:'节目取景',public_event:'公开活动',personal_share:'个人分享',other:'其他'}
const visitableNames:Record<string,string>={open:'正常开放',reservation:'需要预约',closed:'已关闭',private:'私人场所',unknown:'未知'}
const control='min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm outline-none transition focus:border-accent focus:ring-2 focus:ring-red-100'
const splitValues=(value:string)=>value.split(/[,，]/).map(x=>x.trim()).filter(Boolean)

export function AdminShell({children,title,subtitle}:{children:React.ReactNode;title:string;subtitle:string}){
 const pathname=useLocation().pathname
 const{user,signOut}=useAdminAuth()
 const unread=useFeedbackStore(s=>s.items).filter(item=>item.status==='unread').length
 const navClass=(active:boolean)=>`flex min-h-12 items-center gap-3 rounded-xl px-4 transition ${active?'bg-white/15 font-semibold text-white':'text-white/70 hover:bg-white/10 hover:text-white'}`
 return <div className="min-h-[100dvh] bg-slate-100 text-slate-900">
  <aside className="fixed inset-y-0 left-0 w-64 bg-slate-950 p-6 text-white">
   <Link to="/admin/dashboard" className="flex items-center gap-3 text-xl font-black"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent"><MapPin/></span>循迹后台</Link>
   <nav className="mt-10 space-y-2">
    <Link to="/admin/dashboard" aria-current={pathname==='/admin'||pathname==='/admin/dashboard'?'page':undefined} className={navClass(pathname==='/admin'||pathname==='/admin/dashboard')}><LayoutDashboard size={19}/>数据看板</Link>
    <Link to="/admin/place/new" aria-current={pathname.startsWith('/admin/place')||pathname==='/admin/new'?'page':undefined} className={navClass(pathname.startsWith('/admin/place')||pathname==='/admin/new')}><Plus size={19}/>录入地点</Link>
    <Link to="/admin/review" aria-current={pathname==='/admin/review'?'page':undefined} className={navClass(pathname==='/admin/review')}><FileCheck2 size={19}/>审核流程</Link>
    <Link to="/admin/content" aria-current={pathname==='/admin/content'?'page':undefined} className={navClass(pathname==='/admin/content')}><Building2 size={19}/>数据管理</Link>
    <Link to="/admin/feedback" aria-current={pathname==='/admin/feedback'?'page':undefined} className={navClass(pathname==='/admin/feedback')}><MessageSquareText size={19}/>用户反馈{unread>0&&<span className="ml-auto min-w-6 rounded-full bg-orange-500 px-2 py-0.5 text-center text-xs text-white">{unread}</span>}</Link>
    <details open className="group mt-4 border-t border-white/10 pt-4">
     <summary className="flex min-h-11 cursor-pointer list-none items-center justify-between px-4 text-sm font-bold text-white/50">基础数据<span className="transition group-open:rotate-180">⌄</span></summary>
     <div className="mt-1 space-y-1">
      <Link to="/admin/idol/list" aria-current={pathname.startsWith('/admin/idol')?'page':undefined} className={navClass(pathname.startsWith('/admin/idol'))}>爱豆管理</Link>
      <Link to="/admin/work/list" aria-current={pathname.startsWith('/admin/work')?'page':undefined} className={navClass(pathname.startsWith('/admin/work'))}>作品管理</Link>
      <Link to="/admin/city/list" aria-current={pathname.startsWith('/admin/city')?'page':undefined} className={navClass(pathname.startsWith('/admin/city'))}>城市管理</Link>
     </div>
    </details>
   </nav>
   <div className="absolute inset-x-6 bottom-6 space-y-2"><p className="truncate text-xs text-white/35">{user?.email}</p><button type="button" onClick={()=>void signOut()} className="flex min-h-11 w-full items-center gap-2 text-sm text-white/60 hover:text-white"><LogOut size={16}/>退出后台</button><Link to="/" className="flex min-h-11 items-center gap-2 text-sm text-white/60 hover:text-white"><ExternalLink size={16}/>返回用户端</Link></div>
  </aside>
  <main className="ml-64 min-h-[100dvh]"><header className="border-b border-slate-200 bg-white px-10 py-7"><h1 className="text-2xl font-black">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></header><div className="p-10">{children}</div></main>
 </div>
}

export function AdminDashboardPage(){
 const records=useAdminStore(s=>s.records),remove=useAdminStore(s=>s.removeRecord)
 const counts={pending:records.filter(item=>item.status==='pending').length,published:records.filter(item=>item.status==='published').length,rejected:records.filter(item=>item.status==='rejected').length}
 const events=getEvents(),count=(type:string,page?:string)=>events.filter(event=>event.type===type&&(!page||event.page===page)).length,rate=(a:number,b:number)=>b?Math.min(100,Math.round(a/b*100)):0
 const homeViews=count('page_view','home'),placeViews=count('page_view','place_detail'),favorites=count('favorite_click'),routeAdds=count('route_add'),routeGenerates=count('route_generate'),eligibleRoutes=events.filter(event=>event.type==='page_view'&&event.page==='route_builder'&&(event.placeCount||0)>=2).length
 const rates=[['地点详情到达率',rate(placeViews,homeViews),'地点详情 / 首页访问'],['收藏率',rate(favorites,placeViews),'收藏 / 地点详情'],['路线生成率',rate(routeGenerates,eligibleRoutes),'生成 / 可生成路线'],['审核通过率',rate(counts.published,records.length),'已发布 / 全部地点']] as const
 return <AdminShell title="数据看板" subtitle="查看地点审核和发布状态">
  <section className="grid grid-cols-4 gap-5">{rates.map(([label,value,note])=><RateCard key={label} label={label} value={value} note={note}/>)}</section>
  <BackupImportPanel/>
  <AnalyticsPanels events={events} records={records}/>
  <section className="mt-8 grid grid-cols-4 gap-5"><MetricCard label="待审核" value={counts.pending} color="text-amber-600"/><MetricCard label="已发布" value={counts.published} color="text-emerald-600"/><MetricCard label="已驳回" value={counts.rejected} color="text-red-600"/><Link to="/admin/place/new" className="flex items-center justify-center gap-2 rounded-2xl bg-accent px-6 font-bold text-white shadow-sm active:scale-[.99]"><Plus/>录入新地点</Link></section>
  <section className="mt-8 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><h2 className="font-bold">地点列表</h2><span className="text-sm text-slate-400">共 {records.length} 条数据</span></div>
   {records.length===0?<div className="py-20 text-center"><Building2 className="mx-auto text-slate-300" size={42}/><p className="mt-4 font-semibold">还没有录入地点</p><Link to="/admin/place/new" className="mt-3 inline-block text-sm font-semibold text-accent">立即录入第一个地点</Link></div>:
   <table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-6 py-4">地点</th><th>城市与地址</th><th>关联爱豆</th><th>状态</th><th className="pr-6 text-right">操作</th></tr></thead><tbody>{records.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="px-6 py-4 font-semibold">{r.name}</td><td className="max-w-sm truncate pr-5 text-slate-500">{r.city} · {r.address}</td><td>{r.relatedIdols.join('、')||'无'}</td><td><StatusBadge status={r.status}/></td><td className="pr-6 text-right"><button onClick={()=>confirm(`确定删除“${r.name}”吗？`)&&remove(r.id)} aria-label="删除地点" className="inline-flex h-11 w-11 items-center justify-center text-slate-400 hover:text-red-600"><Trash2 size={18}/></button></td></tr>)}</tbody></table>}
  </section>
 </AdminShell>
}

function BackupImportPanel(){
 const admin=useAdminStore(),basic=useBasicDataStore()
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<BackupImportResult|null>(null)
 const choose=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file||busy)return;if(!confirm(`确定将“${file.name}”中的后台数据合并到 Supabase 云端吗？现有同 ID 数据会被更新。`))return;setBusy(true);setError('');setResult(null);try{const backup=parseXunjiBackup(await file.text());const next=await importBackupToCloud(backup);admin.hydrateRecords(backup.places);basic.hydrate({idols:backup.idols,works:backup.works,cities:backup.cities});replaceEvents(backup.events);setResult(next)}catch(reason){setError(reason instanceof Error?reason.message:'导入失败，请重试')}finally{setBusy(false)}}
 const verified=result&&Object.keys(result.expected).every(key=>result.cloud[key as keyof BackupImportResult['cloud']]>=result.expected[key as keyof BackupImportResult['expected']])
 return <section className="mt-8 rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-6"><div><h2 className="flex items-center gap-2 font-black"><UploadCloud className="text-blue-600" size={20}/>云端备份导入与核对</h2><p className="mt-2 text-sm text-slate-500">选择此前导出的 xunji-backup JSON，系统会以 ID 合并到云端并立即回读数量核对。</p></div><label className={`flex min-h-12 cursor-pointer items-center rounded-xl bg-blue-600 px-6 font-bold text-white ${busy?'pointer-events-none opacity-60':''}`}><input type="file" accept="application/json,.json" onChange={choose} className="hidden"/>{busy?'正在上传并核对…':'选择备份文件'}</label></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{error}</p>}{result&&<div className={`mt-4 rounded-xl p-4 text-sm ${verified?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-800'}`}><b>{verified?'云端核对通过':'云端数量需要人工复核'}</b><p className="mt-2">备份：地点 {result.expected.places}、爱豆 {result.expected.idols}、作品 {result.expected.works}、城市 {result.expected.cities}、事件 {result.expected.events}</p><p className="mt-1">云端：地点 {result.cloud.places}、爱豆 {result.cloud.idols}、作品 {result.cloud.works}、城市 {result.cloud.cities}、事件 {result.cloud.events}</p></div>}</section>
}

type FormState={
 name:string;city:string;address:string;lng:string;lat:string;openTime:string;visitable:string;imageUrls:string;
 relatedIdols:string;relatedMovies:string;relatedVariety:string;relatedTV:string;relatedOtherWorks:string;
 relationType:string;relationDesc:string;evidence:string;transportGuide:string;coreSpots:string;tips:string
}
const initial:FormState={name:'',city:'深圳',address:'',lng:'',lat:'',openTime:'',visitable:'open',imageUrls:'',relatedIdols:'',relatedMovies:'',relatedVariety:'',relatedTV:'',relatedOtherWorks:'',relationType:'personal_share',relationDesc:'',evidence:'',transportGuide:'',coreSpots:'',tips:''}

export function AdminPlaceFormPage(){
 const[f,setF]=useState<FormState>(initial),[errors,setErrors]=useState<Record<string,string>>({}),[locating,setLocating]=useState(false),[message,setMessage]=useState(''),[sourceText,setSourceText]=useState(''),[extracting,setExtracting]=useState(false),[extracted,setExtracted]=useState<ExtractedPlaceData|null>(null),[extractError,setExtractError]=useState(''),[toast,setToast]=useState('')
 const add=useAdminStore(s=>s.addRecord),navigate=useNavigate()
 const basic=useBasicDataStore()
 const idolNames=splitValues(f.relatedIdols),newIdolNames=idolNames.filter(name=>!basic.idols.some(idol=>idol.name.toLowerCase()===name.toLowerCase()))
 const set=(key:keyof FormState,value:string)=>{setF(x=>({...x,[key]:value}));setErrors(x=>({...x,[key]:''}))}
 const toggleChoice=(key:keyof FormState,value:string)=>{const values=splitValues(f[key]);set(key,(values.includes(value)?values.filter(x=>x!==value):[...values,value]).join(','))}
 const locate=async()=>{if(!f.address.trim()){setErrors(x=>({...x,address:'请先填写详细地址'}));return}setLocating(true);setMessage('高德地图暂未接入，请手动填写经纬度');setLocating(false)}
 const extract=async()=>{if(!sourceText.trim()){setExtractError('请先粘贴需要提取的内容');return}setExtracting(true);setExtractError('');try{setExtracted(await extractPlaceFromText(sourceText,basic.idols,{name:f.name,city:f.city,address:f.address}))}catch(error){setExtractError(error instanceof Error?error.message:'提取失败，请稍后重试')}finally{setExtracting(false)}}
 const applyExtracted=()=>{if(!extracted)return;setF(x=>({...x,name:extracted.name||x.name,address:extracted.address||x.address,city:extracted.city||x.city,relatedIdols:extracted.idolName||x.relatedIdols,relationType:extracted.relationType,relationDesc:extracted.relationDescription,evidence:extracted.evidenceSource,transportGuide:extracted.transportGuide||x.transportGuide,coreSpots:extracted.coreSpots||x.coreSpots,tips:extracted.tips||x.tips}));setExtracted(null);setMessage('AI 提取结果已填入表单，请继续核对')}
 const submit=async(event:FormEvent)=>{event.preventDefault();const required:{key:keyof FormState;label:string}[]=[{key:'name',label:'地点名称'},{key:'city',label:'城市'},{key:'address',label:'详细地址'},{key:'lng',label:'经度'},{key:'lat',label:'纬度'},{key:'openTime',label:'开放时间'},{key:'visitable',label:'可到访性'},{key:'relationType',label:'关系类型'},{key:'relationDesc',label:'关系说明'},{key:'evidence',label:'证据来源'}];const next:Record<string,string>={};required.forEach(({key,label})=>{if(!f[key].trim())next[key]=`${label}为必填项`});if(!Number.isFinite(Number(f.lng)))next.lng='请输入有效经度';if(!Number.isFinite(Number(f.lat)))next.lat='请输入有效纬度';setErrors(next);if(Object.keys(next).length)return
  const cityName=f.city.trim();const existingCity=basic.cities.find(city=>city.name.toLowerCase()===cityName.toLowerCase());const cityId=existingCity?.id||`city-auto-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;if(!existingCity){const knownRegions:Record<string,string>={深圳:'广东省',上海:'上海市',重庆:'重庆市',北京:'北京市'};if(!await basic.addCity({id:cityId,name:cityName,region:knownRegions[cityName]||'待补充',cover:'',story:'',iconUrl:'',placeCount:0,routeCount:0,autoCreated:true,createdAt:new Date().toISOString()}))return}const names=splitValues(f.relatedIdols),idolIds:string[]=[];for(const name of names){const existing=basic.idols.find(idol=>idol.name.toLowerCase()===name.toLowerCase());if(existing){const cities=cityId&&!existing.cities.includes(cityId)?[...existing.cities,cityId]:existing.cities;const cityNames=existing.cityNames?.includes(cityName)?existing.cityNames:[...(existing.cityNames||[]),cityName];if(!await basic.updateIdol(existing.id,{cities,cityNames}))return;idolIds.push(existing.id)}else{const id=`idol-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;if(!await basic.addIdol({id,name,avatar:'',roles:[],bio:'',cities:[cityId],cityNames:[cityName],fanName:'',placeCount:0,createdAt:new Date().toISOString()}))return;idolIds.push(id)}}
  if(!await add({id:`place-${Date.now()}`,name:f.name.trim(),city:f.city.trim(),address:f.address.trim(),lng:Number(f.lng),lat:Number(f.lat),openTime:f.openTime.trim(),visitable:f.visitable,images:splitValues(f.imageUrls),relatedIdols:names,relatedIdolNames:names,relatedIdolIds:idolIds,relatedMovies:splitValues(f.relatedMovies),relatedVariety:splitValues(f.relatedVariety),relatedTV:splitValues(f.relatedTV),relatedOtherWorks:splitValues(f.relatedOtherWorks),relationType:f.relationType,relationDesc:f.relationDesc.trim(),evidence:f.evidence.trim(),transportGuide:f.transportGuide.trim()||undefined,coreSpots:f.coreSpots.trim()||undefined,tips:f.tips.trim()||undefined,credibility:null,status:'pending',createdAt:new Date().toISOString()}))return
  setF(initial);setSourceText('');setToast('地点已保存，等待审核');setTimeout(()=>navigate('/admin/dashboard'),900)
 }
 return <AdminShell title="录入地点" subtitle="保存后进入待审核队列，可信度将在审核流程中设置">
  {toast&&<div role="status" className="fixed right-8 top-8 z-50 rounded-xl bg-emerald-700 px-5 py-4 font-semibold text-white shadow-xl">{toast}</div>}
  <form onSubmit={submit} noValidate className="mx-auto max-w-5xl">
   <section className="mb-6 rounded-2xl bg-slate-950 p-8 text-white shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent"><Sparkles size={21}/></span><div><h2 className="text-lg font-black">AI 智能提取与攻略生成</h2><p className="mt-1 text-sm text-white/55">识别原文信息，并补全交通、打卡路线和小贴士草稿</p></div></div><div className="mt-6 flex items-stretch gap-3"><textarea value={sourceText} onChange={e=>{setSourceText(e.target.value);setExtractError('')}} rows={5} placeholder="粘贴微博/小红书/豆瓣等内容，AI 自动识别地点并生成攻略草稿" className="w-full resize-y rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm text-white outline-none placeholder:text-white/35 focus:border-accent"/><button type="button" onClick={extract} disabled={extracting} className="min-w-40 rounded-xl bg-accent px-5 font-bold text-white disabled:opacity-60">{extracting?'生成中...':'提取并生成攻略'}</button></div><p className="mt-3 text-xs leading-5 text-white/45">AI 不会主动编造具体线路、出口、票价或营业时间；生成内容必须在发布前人工核实。</p>{extractError&&<p className="mt-2 text-sm text-red-300">{extractError}</p>}</section>
   {extracted&&<section className="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-start justify-between gap-6"><div><div className="flex items-center gap-3"><h2 className="font-black text-emerald-900">识别与攻略草稿</h2><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{extracted.extractionMode==='ai'?'AI 生成':'本地规则草稿'} · 待核实</span></div>{extracted.guideNotice&&<p className="mt-3 rounded-xl bg-white/70 px-4 py-3 text-xs leading-5 text-amber-800">{extracted.guideNotice}</p>}<div className="mt-4 grid grid-cols-2 gap-x-10 gap-y-3 text-sm"><Result label="地点名称" value={extracted.name}/><Result label="城市" value={extracted.city}/><Result label="地址" value={extracted.address}/><Result label="关联爱豆" value={extracted.idolName}/><Result label="关系类型" value={relationNames[extracted.relationType]}/><Result label="交通指南" value={extracted.transportGuide}/><Result label="核心打卡点" value={extracted.coreSpots}/><Result label="游玩小贴士" value={extracted.tips}/></div></div><button type="button" onClick={applyExtracted} className="min-h-12 shrink-0 rounded-xl bg-emerald-700 px-6 font-bold text-white">确认并填充表单</button></div></section>}
   <section className="rounded-2xl bg-white p-8 shadow-sm"><SectionTitle number="01" title="地点信息"/><div className="mt-6 grid grid-cols-2 gap-6">
    <Field label="地点名称 *" error={errors.name}><Input value={f.name} onChange={v=>set('name',v)} placeholder="例如：深圳人才公园"/></Field>
    <Field label="城市 *" error={errors.city}><input required list="place-city-options" value={f.city} onChange={e=>set('city',e.target.value)} className={control} placeholder="输入或选择城市"/><datalist id="place-city-options">{basic.cities.map(city=><option key={city.id} value={city.name}/>)}</datalist><span className="mt-1.5 block font-normal text-slate-400">输入新城市时会自动创建城市资料，可稍后在城市管理中补充。</span></Field>
    <div className="col-span-2"><Field label="详细地址 *" error={errors.address}><div className="flex gap-3"><Input value={f.address} onChange={v=>set('address',v)} placeholder="填写完整地址"/><button type="button" onClick={locate} disabled={locating} className="min-w-32 rounded-xl bg-slate-900 px-4 font-semibold text-white disabled:opacity-50">解析坐标</button></div></Field>{message&&<p className="mt-2 text-sm text-amber-600">{message}</p>}</div>
    <Field label="经度 *" error={errors.lng}><Input value={f.lng} onChange={v=>set('lng',v)} placeholder="113.941"/></Field><Field label="纬度 *" error={errors.lat}><Input value={f.lat} onChange={v=>set('lat',v)} placeholder="22.515"/></Field>
    <Field label="开放时间 *" error={errors.openTime}><Input value={f.openTime} onChange={v=>set('openTime',v)} placeholder="例如：06:00-23:00"/></Field>
    <Field label="可到访性 *" error={errors.visitable}><select value={f.visitable} onChange={e=>set('visitable',e.target.value)} className={control}>{Object.entries(visitableNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field>
    <div className="col-span-2"><Field label="地点图片（选填）"><Input value={f.imageUrls} onChange={v=>set('imageUrls',v)} placeholder="可粘贴多个图片 URL（用逗号分隔）"/><ImageUploadControl value={f.imageUrls} onChange={v=>set('imageUrls',v)} folder="places" multiple/></Field></div>
   </div></section>
   <section className="mt-6 rounded-2xl bg-white p-8 shadow-sm"><SectionTitle number="02" title="关联与证据"/><div className="mt-6 grid grid-cols-2 gap-6">
    <div className="col-span-2"><Field label="关联爱豆"><input list="idol-suggestions" value={f.relatedIdols} onChange={event=>set('relatedIdols',event.target.value)} className={control} placeholder="输入爱豆名字，多个用逗号分隔，例如：RIIZE、周深"/><datalist id="idol-suggestions">{basic.idols.map(idol=><option key={idol.id} value={idol.name}/>)}</datalist>{newIdolNames.length>0&&<p className="mt-2 font-normal text-orange-600">将自动创建 Idol 主页：{newIdolNames.join('、')}</p>}{f.relatedIdols&&newIdolNames.length===0&&<p className="mt-2 font-normal text-emerald-600">已匹配现有 Idol 资料</p>}</Field></div>
    <div className="col-span-2"><Field label="关联电影"><ChoiceGrid empty="暂无电影作品" items={basic.works.filter(x=>x.type==='movie').map(x=>x.name)} selected={splitValues(f.relatedMovies)} onToggle={value=>toggleChoice('relatedMovies',value)}/></Field></div>
    <div className="col-span-2"><Field label="关联综艺"><ChoiceGrid empty="暂无综艺作品" items={basic.works.filter(x=>x.type==='variety').map(x=>x.name)} selected={splitValues(f.relatedVariety)} onToggle={value=>toggleChoice('relatedVariety',value)}/></Field></div>
    <div className="col-span-2"><Field label="关联电视剧"><ChoiceGrid empty="暂无电视剧作品" items={basic.works.filter(x=>x.type==='tv').map(x=>x.name)} selected={splitValues(f.relatedTV)} onToggle={value=>toggleChoice('relatedTV',value)}/></Field></div>
    <div className="col-span-2"><Field label="关联书籍、音乐或其他作品"><ChoiceGrid empty="暂无其他类型作品" items={basic.works.filter(x=>['book','music','other'].includes(x.type)).map(x=>x.name)} selected={splitValues(f.relatedOtherWorks)} onToggle={value=>toggleChoice('relatedOtherWorks',value)}/></Field></div>
    <Field label="关系类型 *" error={errors.relationType}><select value={f.relationType} onChange={e=>set('relationType',e.target.value)} className={control}>{Object.entries(relationNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><div/>
    <div className="col-span-2"><Field label="关系说明 *" error={errors.relationDesc}><textarea value={f.relationDesc} onChange={e=>set('relationDesc',e.target.value)} rows={4} className={control} placeholder="说明爱豆或作品与地点之间的公开关系"/></Field><p className="mt-1.5 text-xs text-slate-400">例如：周杰伦在此拍摄《最伟大的作品》MV</p></div>
    <div className="col-span-2"><Field label="证据来源 *" error={errors.evidence}><textarea value={f.evidence} onChange={e=>set('evidence',e.target.value)} rows={3} className={control} placeholder="填写公开账号、节目正片、媒体报道或投稿说明"/></Field><p className="mt-1.5 text-xs text-slate-400">例如：微博@周杰伦官方账号 2024年3月发布</p></div>
   </div></section>
   <section className="mt-6 rounded-2xl bg-white p-8 shadow-sm"><SectionTitle number="03" title="攻略信息"/><p className="mt-2 text-sm text-slate-400">以下信息均为选填</p><div className="mt-6 space-y-6">
    <Field label="交通指南"><textarea value={f.transportGuide} onChange={e=>set('transportGuide',e.target.value)} rows={4} className={`${control} py-3`} placeholder="例如：地铁13号线到深圳湾口岸站A口出，步行约5-7分钟..."/></Field>
    <Field label="核心打卡点与路线"><textarea value={f.coreSpots} onChange={e=>set('coreSpots',e.target.value)} rows={5} className={`${control} py-3`} placeholder="例如：1. 日出剧场楼梯与地标：从正门进... 2. 大椰子与City不City打卡位..."/></Field>
    <Field label="游玩小贴士"><textarea value={f.tips} onChange={e=>set('tips',e.target.value)} rows={5} className={`${control} py-3`} placeholder="例如：最佳时间：推荐傍晚前往... 游玩时长：整体逛下来大概需要1到1.5小时..."/></Field>
   </div></section>
   <div className="mt-6 flex justify-end gap-3"><Link to="/admin/dashboard" className="flex min-h-12 items-center gap-2 rounded-xl border border-slate-300 px-6 font-semibold"><ArrowLeft size={18}/>取消</Link><button type="submit" className="min-h-12 rounded-xl bg-accent px-9 font-bold text-white active:scale-[.99]">保存地点</button></div>
  </form>
 </AdminShell>
}

function Input({value,onChange,placeholder}:{value:string;onChange:(value:string)=>void;placeholder:string}){return <input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={control}/>}
function ChoiceGrid({items,selected,onToggle,empty}:{items:string[];selected:string[];onToggle:(value:string)=>void;empty:string}){return items.length?<div className="grid grid-cols-3 gap-2">{items.map(item=><label key={item} className={`flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border px-3 font-normal ${selected.includes(item)?'border-red-400 bg-red-50 text-red-700':'border-slate-200 bg-white'}`}><input type="checkbox" checked={selected.includes(item)} onChange={()=>onToggle(item)}/>{item}</label>)}</div>:<div className="rounded-xl border border-dashed border-slate-300 px-4 py-5 font-normal text-slate-400">{empty}</div>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-semibold text-slate-700"><span className="mb-2 block">{label}</span>{children}{error&&<span className="mt-1.5 block font-normal text-red-600">{error}</span>}</label>}
function SectionTitle({number,title}:{number:string;title:string}){return <div className="flex items-center gap-3"><span className="text-sm font-black text-accent">{number}</span><h2 className="text-lg font-black">{title}</h2></div>}
function Result({label,value}:{label:string;value?:string}){const wide=['交通指南','核心打卡点','游玩小贴士'].includes(label);return <div className={wide?'col-span-2 rounded-xl bg-white/70 p-4':'rounded-lg py-1'}><span className="text-emerald-700">{label}：</span><strong className={`${wide?'mt-2 block whitespace-pre-line font-medium leading-6':'text-emerald-950'}`}>{value||'未识别'}</strong></div>}

const credibilityMeta:Record<Credibility,{title:string;description:string;className:string}>={
 A:{title:'A · 官方认证',description:'官方发布、节目正片、本人公开内容等直接证据',className:'border-emerald-500 bg-emerald-50 text-emerald-800'},
 B:{title:'B · 多源印证',description:'多个可靠公开来源互相印证',className:'border-blue-500 bg-blue-50 text-blue-800'},
 C:{title:'C · 单一来源',description:'单一非官方来源或用户投稿，待进一步核验',className:'border-orange-500 bg-orange-50 text-orange-800'},
 D:{title:'D · 氛围联想',description:'氛围或创作联想，仅供参考',className:'border-slate-400 bg-slate-100 text-slate-700'}
}
const statusMeta={pending:['待审核','bg-amber-100 text-amber-700'],published:['已发布','bg-emerald-100 text-emerald-700'],rejected:['已驳回','bg-red-100 text-red-700']} as const
const joinedWorks=(item:AdminPlace)=>[...item.relatedMovies,...item.relatedVariety,...item.relatedTV,...(item.relatedOtherWorks||[])].join('、')

export function AdminReviewPage(){
 const records=useAdminStore(s=>s.records),reviewRecord=useAdminStore(s=>s.reviewRecord)
 const[selected,setSelected]=useState<AdminPlace|null>(null),[credibility,setCredibility]=useState<Credibility|null>(null),[opinion,setOpinion]=useState(''),[error,setError]=useState('')
 const open=(item:AdminPlace)=>{setSelected(item);setCredibility(item.credibility);setOpinion(item.reviewNote||item.reviewOpinion||'');setError('')}
 const decide=async(status:'published'|'rejected')=>{if(!selected)return;if(status==='published'&&!credibility){setError('审核通过前必须设置可信度');return}if(status==='rejected'&&!opinion.trim()){setError('驳回时必须填写审核意见');return}if(!await reviewRecord(selected.id,status,status==='published'?credibility:selected.credibility,opinion.trim()))return;recalculateBasicCounts(useAdminStore.getState().records);setSelected(null)}
 return <AdminShell title="审核流程" subtitle="核验公开证据，设置可信度后发布地点">
  <section className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="min-w-[1180px] w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-6 py-4">地点名称</th><th>城市</th><th>关联爱豆</th><th>关联作品</th><th>关系类型</th><th>证据来源</th><th>状态</th><th className="pr-6 text-right">操作</th></tr></thead><tbody>{records.map(item=><tr key={item.id} className="border-t border-slate-100"><td className="px-6 py-4 font-semibold">{item.name}</td><td>{item.city}</td><td className="max-w-40">{item.relatedIdols.join('、')||'无'}</td><td className="max-w-56 truncate">{joinedWorks(item)||'无'}</td><td>{relationNames[item.relationType]||item.relationType}</td><td className="max-w-56">{item.evidence.length>30?`${item.evidence.slice(0,30)}...`:item.evidence}</td><td><StatusBadge status={item.status}/></td><td className="pr-6 text-right"><button onClick={()=>open(item)} className="min-h-10 rounded-lg bg-slate-900 px-4 font-semibold text-white">审核</button></td></tr>)}</tbody></table>{records.length===0&&<div className="py-20 text-center text-slate-500">暂无待审核数据</div>}</section>
  {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/55" onMouseDown={event=>event.target===event.currentTarget&&setSelected(null)}><aside className="h-full w-[620px] overflow-y-auto bg-white p-8 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">地点审核</p><h2 className="mt-1 text-2xl font-black">{selected.name}</h2></div><button onClick={()=>setSelected(null)} className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100"><X/></button></div>
   <div className="mt-7 grid grid-cols-2 gap-4 rounded-2xl bg-slate-50 p-5 text-sm"><Detail label="城市" value={selected.city}/><Detail label="地址" value={selected.address}/><Detail label="坐标" value={`${selected.lng}, ${selected.lat}`}/><Detail label="开放时间" value={selected.openTime}/><Detail label="可到访性" value={visitableNames[selected.visitable]||selected.visitable}/><Detail label="关系类型" value={relationNames[selected.relationType]||selected.relationType}/><Detail label="关联爱豆" value={selected.relatedIdols.join('、')||'无'}/><Detail label="关联作品" value={joinedWorks(selected)||'无'}/><div className="col-span-2"><Detail label="关系说明" value={selected.relationDesc}/></div><div className="col-span-2"><Detail label="证据来源" value={selected.evidence}/></div>{selected.transportGuide&&<div className="col-span-2"><Detail label="交通指南" value={selected.transportGuide}/></div>}{selected.coreSpots&&<div className="col-span-2"><Detail label="核心打卡点" value={selected.coreSpots}/></div>}{selected.tips&&<div className="col-span-2"><Detail label="游玩小贴士" value={selected.tips}/></div>}{selected.images.length>0&&<div className="col-span-2 flex gap-2 overflow-x-auto">{selected.images.map((url,index)=><img key={`${url}-${index}`} src={url} className="h-24 w-32 shrink-0 rounded-xl object-cover" alt="地点参考图"/>)}</div>}</div>
   <h3 className="mt-8 font-black">可信度设置 *</h3><div className="mt-3 space-y-3">{(Object.keys(credibilityMeta) as Credibility[]).map(level=>{const meta=credibilityMeta[level];return <button type="button" key={level} onClick={()=>{setCredibility(level);setError('')}} className={`w-full rounded-xl border-2 p-4 text-left transition ${credibility===level?meta.className:'border-slate-200 hover:border-slate-300'}`}><strong>{meta.title}</strong><p className="mt-1 text-sm opacity-80">{meta.description}</p></button>})}</div>
   <label className="mt-6 block text-sm font-semibold">审核意见（驳回时必填）<textarea value={opinion} onChange={event=>{setOpinion(event.target.value);setError('')}} rows={4} className={`${control} mt-2 py-3`} placeholder="填写核验结果、补充说明或驳回原因"/></label>{error&&<p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}
   <div className="mt-7 grid grid-cols-2 gap-3"><button onClick={()=>decide('rejected')} className="min-h-12 rounded-xl border border-red-300 font-bold text-red-700">驳回</button><button onClick={()=>decide('published')} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-700 font-bold text-white"><Check size={18}/>通过并发布</button></div>
  </aside></div>}
 </AdminShell>
}

export function AdminContentPage(){
 const records=useAdminStore(s=>s.records),remove=useAdminStore(s=>s.removeRecord),update=useAdminStore(s=>s.updateRecord)
 const[params]=useSearchParams()
 const[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[city,setCity]=useState('all'),[editing,setEditing]=useState<AdminPlace|null>(()=>records.find(item=>item.id===params.get('edit'))||null)
 const cities=[...new Set(records.map(item=>item.city))].sort()
 const filtered=records.filter(item=>{const haystack=[item.name,...item.relatedIdols,...item.relatedMovies,...item.relatedVariety,...item.relatedTV,...(item.relatedOtherWorks||[])].join(' ').toLowerCase();return haystack.includes(query.toLowerCase())&&(status==='all'||item.status===status)&&(city==='all'||item.city===city)})
 return <AdminShell title="数据管理" subtitle="搜索、筛选、编辑和删除全部地点数据">
  <section className="mb-6 grid grid-cols-[1fr_180px_180px] gap-3 rounded-2xl bg-white p-5 shadow-sm"><label className="flex min-h-12 items-center gap-3 rounded-xl border border-slate-300 px-4"><Search size={18} className="text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-full outline-none" placeholder="搜索地点、爱豆或作品"/></label><select value={status} onChange={event=>setStatus(event.target.value)} className={control}><option value="all">全部状态</option><option value="pending">待审核</option><option value="published">已发布</option><option value="rejected">已驳回</option></select><select value={city} onChange={event=>setCity(event.target.value)} className={control}><option value="all">全部城市</option>{cities.map(value=><option key={value}>{value}</option>)}</select></section>
  <section className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-6 py-4">地点</th><th>城市</th><th>关联爱豆</th><th>关联作品</th><th>关系类型</th><th>状态</th><th className="pr-6 text-right">操作</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} className="border-t border-slate-100"><td className="px-6 py-4 font-semibold">{item.name}</td><td>{item.city}</td><td>{item.relatedIdols.join('、')||'无'}</td><td className="max-w-64 truncate">{joinedWorks(item)||'无'}</td><td>{relationNames[item.relationType]||item.relationType}</td><td><StatusBadge status={item.status}/></td><td className="pr-6 text-right"><button onClick={()=>setEditing(item)} className="inline-flex h-11 w-11 items-center justify-center text-slate-500 hover:text-blue-600" aria-label="编辑"><Edit3 size={18}/></button><button onClick={()=>confirm(`确定删除“${item.name}”吗？此操作无法恢复。`)&&remove(item.id)} className="inline-flex h-11 w-11 items-center justify-center text-slate-500 hover:text-red-600" aria-label="删除"><Trash2 size={18}/></button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="py-20 text-center text-slate-500">没有符合筛选条件的地点</div>}</section>
  {editing&&<EditPlaceModal place={editing} onClose={()=>setEditing(null)} onSave={async changes=>{if(await update(editing.id,changes))setEditing(null)}}/>}
 </AdminShell>
}

function EditPlaceModal({place,onClose,onSave}:{place:AdminPlace;onClose:()=>void;onSave:(changes:Partial<AdminPlace>)=>Promise<void>}){
 const[draft,setDraft]=useState({...place,images:place.images.join('，'),relatedIdols:place.relatedIdols.join('，'),relatedMovies:place.relatedMovies.join('，'),relatedVariety:place.relatedVariety.join('，'),relatedTV:place.relatedTV.join('，')})
 const save=async(event:FormEvent)=>{event.preventDefault();if(!draft.name.trim()||!draft.city.trim()||!draft.address.trim()){return}await onSave({...draft,lng:Number(draft.lng),lat:Number(draft.lat),images:splitValues(draft.images),relatedIdols:splitValues(draft.relatedIdols),relatedMovies:splitValues(draft.relatedMovies),relatedVariety:splitValues(draft.relatedVariety),relatedTV:splitValues(draft.relatedTV)})}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-8" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><form onSubmit={save} className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-8 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">编辑地点</h2><button type="button" onClick={onClose} className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100"><X/></button></div><div className="mt-6 grid grid-cols-2 gap-5">
  <EditInput label="地点名称 *" value={draft.name} onChange={value=>setDraft({...draft,name:value})}/><EditInput label="城市 *" value={draft.city} onChange={value=>setDraft({...draft,city:value})}/><div className="col-span-2"><EditInput label="地址 *" value={draft.address} onChange={value=>setDraft({...draft,address:value})}/></div><EditInput label="经度" value={String(draft.lng)} onChange={value=>setDraft({...draft,lng:Number(value)})}/><EditInput label="纬度" value={String(draft.lat)} onChange={value=>setDraft({...draft,lat:Number(value)})}/><EditInput label="开放时间" value={draft.openTime} onChange={value=>setDraft({...draft,openTime:value})}/><label className="text-sm font-semibold">可到访性<select value={draft.visitable} onChange={event=>setDraft({...draft,visitable:event.target.value})} className={`${control} mt-2`}>{Object.entries(visitableNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="col-span-2"><EditInput label="图片 URL" value={draft.images} onChange={value=>setDraft({...draft,images:value})}/><ImageUploadControl value={draft.images} onChange={images=>setDraft({...draft,images})} folder="places" multiple/></div><EditInput label="关联爱豆" value={draft.relatedIdols} onChange={value=>setDraft({...draft,relatedIdols:value})}/><EditInput label="关联电影" value={draft.relatedMovies} onChange={value=>setDraft({...draft,relatedMovies:value})}/><EditInput label="关联综艺" value={draft.relatedVariety} onChange={value=>setDraft({...draft,relatedVariety:value})}/><EditInput label="关联电视剧" value={draft.relatedTV} onChange={value=>setDraft({...draft,relatedTV:value})}/><label className="text-sm font-semibold">关系类型<select value={draft.relationType} onChange={event=>setDraft({...draft,relationType:event.target.value})} className={`${control} mt-2`}>{Object.entries(relationNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold">状态<select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value as AdminPlace['status']})} className={`${control} mt-2`}><option value="pending">待审核</option><option value="published">已发布</option><option value="rejected">已驳回</option></select></label><div className="col-span-2"><EditText label="关系说明" value={draft.relationDesc} onChange={value=>setDraft({...draft,relationDesc:value})}/></div><div className="col-span-2"><EditText label="证据来源" value={draft.evidence} onChange={value=>setDraft({...draft,evidence:value})}/></div><div className="col-span-2"><EditText label="交通指南" value={draft.transportGuide||''} onChange={value=>setDraft({...draft,transportGuide:value})}/></div><div className="col-span-2"><EditText label="核心打卡点与路线" value={draft.coreSpots||''} onChange={value=>setDraft({...draft,coreSpots:value})}/></div><div className="col-span-2"><EditText label="游玩小贴士" value={draft.tips||''} onChange={value=>setDraft({...draft,tips:value})}/></div>
 </div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onClose} className="min-h-12 rounded-xl border border-slate-300 px-6 font-semibold">取消</button><button type="submit" className="min-h-12 rounded-xl bg-slate-900 px-8 font-bold text-white">保存修改</button></div></form></div>
}
function StatusBadge({status}:{status:AdminPlace['status']}){const meta=statusMeta[status];return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${meta[1]}`}>{meta[0]}</span>}
function RateCard({label,value,note}:{label:string;value:number;note:string}){return <article className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><p className="text-sm font-semibold text-slate-500">{label}</p><span className="rounded-full bg-orange-50 px-2 py-1 text-xs text-orange-600">转化</span></div><p className="mt-4 text-4xl font-black">{value}%</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-orange-500" style={{width:`${value}%`}}/></div><p className="mt-2 text-xs text-slate-400">{note}</p></article>}
function AnalyticsPanels({events,records}:{events:XunjiEvent[];records:AdminPlace[]}){
 const since=Date.now()-7*86400000,recent=events.filter(event=>new Date(event.time).getTime()>=since)
 const days=Array.from({length:7},(_,index)=>{const date=new Date(Date.now()-(6-index)*86400000),key=date.toISOString().slice(0,10);return{key,label:`${date.getMonth()+1}/${date.getDate()}`,value:recent.filter(event=>event.type==='page_view'&&event.time.slice(0,10)===key).length}})
 const maxDay=Math.max(1,...days.map(day=>day.value))
 const placeScores=new Map<string,number>();events.forEach(event=>{if(event.placeId&&(event.type==='favorite_click'||(event.type==='page_view'&&event.page==='place_detail')))placeScores.set(event.placeId,(placeScores.get(event.placeId)||0)+(event.type==='favorite_click'?2:1))})
 const topPlaces=[...placeScores].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([id,value])=>({name:records.find(item=>item.id===id)?.name||id,value}))
 const searchScores=new Map<string,number>();events.forEach(event=>{if(event.type==='search_submit'&&event.keyword)searchScores.set(event.keyword,(searchScores.get(event.keyword)||0)+1)})
 const topSearches=[...searchScores].sort((a,b)=>b[1]-a[1]).slice(0,5)
 const funnel=[['首页',events.filter(e=>e.type==='page_view'&&e.page==='home').length],['地点详情',events.filter(e=>e.type==='page_view'&&e.page==='place_detail').length],['收藏',events.filter(e=>e.type==='favorite_click').length],['加入路线',events.filter(e=>e.type==='route_add').length],['生成路线',events.filter(e=>e.type==='route_generate').length]] as const
 const funnelMax=Math.max(1,...funnel.map(([,value])=>value))
 return <section className="mt-8 grid grid-cols-2 gap-6"><article className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-black">近 7 天页面访问趋势</h2><div className="mt-6 flex h-48 items-end gap-3 border-b border-slate-200 px-2">{days.map(day=><div key={day.key} className="flex h-full flex-1 flex-col items-center justify-end"><span className="mb-2 text-xs font-bold">{day.value}</span><div className="w-full rounded-t-lg bg-orange-400" style={{height:`${Math.max(4,day.value/maxDay*130)}px`}}/><span className="mt-2 text-[10px] text-slate-400">{day.label}</span></div>)}</div></article><article className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-black">转化率漏斗</h2><div className="mt-5 space-y-3">{funnel.map(([label,value],index)=><div key={label} className="flex items-center gap-3"><span className="w-16 text-xs text-slate-500">{label}</span><div className="h-8 flex-1 overflow-hidden rounded-lg bg-slate-100"><div className={`flex h-full items-center px-3 text-xs font-bold text-white ${index===0?'bg-slate-800':'bg-orange-500'}`} style={{width:`${Math.max(12,value/funnelMax*100)}%`}}>{value}</div></div></div>)}</div></article><RankPanel title="热门地点 Top 5" rows={topPlaces.map(item=>[item.name,item.value])}/><RankPanel title="热门搜索词 Top 5" rows={topSearches}/></section>
}
function RankPanel({title,rows}:{title:string;rows:[string,number][]}){return <article className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-black">{title}</h2><div className="mt-4 space-y-3">{rows.map(([name,value],index)=><div key={name} className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold">{index+1}</span><span className="flex-1 truncate text-sm">{name}</span><b className="text-sm">{value}</b></div>)}{!rows.length&&<p className="py-8 text-center text-sm text-slate-400">等待用户行为数据</p>}</div></article>}
function MetricCard({label,value,color}:{label:string;value:number;color:string}){return <div className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className={`mt-3 text-4xl font-black ${color}`}>{value}</p></div>}
function Detail({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 leading-6 text-slate-700">{value}</p></div>}
function EditInput({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="text-sm font-semibold">{label}<input required={label.includes('*')} value={value} onChange={event=>onChange(event.target.value)} className={`${control} mt-2`}/></label>}
function EditText({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="text-sm font-semibold">{label}<textarea value={value} onChange={event=>onChange(event.target.value)} rows={3} className={`${control} mt-2 py-3`}/></label>}
