import {Check,Eye,MessageSquareReply,Trash2,X} from 'lucide-react'
import {useState} from 'react'
import {AdminShell} from './Admin'
import {useFeedbackStore,type Feedback} from '../stores'
const typeNames={bug:'Bug',suggestion:'建议',correction:'内容纠错'}
const statusNames={unread:'未读',read:'已读',replied:'已回复'}
const statusClass={unread:'bg-orange-100 text-orange-700',read:'bg-blue-100 text-blue-700',replied:'bg-emerald-100 text-emerald-700'}
export function AdminFeedbackPage(){
 const items=useFeedbackStore(s=>s.items),markRead=useFeedbackStore(s=>s.markRead),reply=useFeedbackStore(s=>s.reply),remove=useFeedbackStore(s=>s.remove),[selected,setSelected]=useState<Feedback|null>(null),[draft,setDraft]=useState('')
 const open=(item:Feedback)=>{setSelected(item);setDraft(item.reply||'');markRead(item.id)}
 const send=async()=>{if(!selected||!draft.trim())return;if(await reply(selected.id,draft.trim()))setSelected(null)}
 return <AdminShell title="用户反馈" subtitle="查看并处理来自用户端的意见、建议与内容纠错"><section className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-6 py-4">类型</th><th>内容摘要</th><th>联系方式</th><th>状态</th><th>提交时间</th><th className="pr-6 text-right">操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-slate-100"><td className="px-6 py-4 font-semibold">{typeNames[item.type]}</td><td className="max-w-md truncate pr-5">{item.content.length>45?`${item.content.slice(0,45)}…`:item.content}</td><td>{item.contact||'—'}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass[item.status]}`}>{statusNames[item.status]}</span></td><td>{new Date(item.createdAt).toLocaleString('zh-CN')}</td><td className="pr-6"><div className="flex justify-end"><Action title="查看详情" onClick={()=>open(item)}><Eye size={18}/></Action>{item.status==='unread'&&<Action title="标记已读" onClick={()=>markRead(item.id)}><Check size={18}/></Action>}<Action title="回复" onClick={()=>open(item)}><MessageSquareReply size={18}/></Action><Action title="删除" danger onClick={()=>confirm('确定删除这条反馈吗？')&&remove(item.id)}><Trash2 size={18}/></Action></div></td></tr>)}</tbody></table>{!items.length&&<div className="py-20 text-center text-slate-400">暂无用户反馈</div>}</section>{selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-8" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="w-full max-w-2xl rounded-2xl bg-white p-8 shadow-2xl"><div className="flex justify-between"><div><p className="text-sm text-slate-400">{typeNames[selected.type]} · {new Date(selected.createdAt).toLocaleString('zh-CN')}</p><h2 className="mt-1 text-2xl font-black">反馈详情</h2></div><button onClick={()=>setSelected(null)} className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100"><X/></button></div><div className="mt-6 rounded-xl bg-slate-50 p-5 leading-7 text-slate-700">{selected.content}</div><p className="mt-3 text-sm text-slate-500">联系方式：{selected.contact||'未填写'}</p><label className="mt-6 block text-sm font-bold">回复内容<textarea rows={5} value={draft} onChange={e=>setDraft(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-4 font-normal outline-none focus:border-orange-500" placeholder="填写回复内容"/></label><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setSelected(null)} className="min-h-12 rounded-xl border px-6 font-semibold">取消</button><button onClick={send} disabled={!draft.trim()} className="min-h-12 rounded-xl bg-slate-950 px-7 font-bold text-white disabled:opacity-40">发送回复</button></div></div></div>}</AdminShell>
}
function Action({title,onClick,danger=false,children}:{title:string;onClick:()=>void;danger?:boolean;children:React.ReactNode}){return <button title={title} onClick={onClick} className={`flex h-11 w-11 items-center justify-center ${danger?'text-slate-400 hover:text-red-600':'text-slate-500 hover:text-blue-600'}`}>{children}</button>}
