import {FormEvent,useEffect,useState} from 'react'
import {Edit3,ExternalLink,Image,Plus,Search,Trash2,X} from 'lucide-react'
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom'
import {AdminShell} from './Admin'
import {recalculateBasicCounts,useAdminStore,useBasicDataStore,type AdminPlace,type ManagedCity,type ManagedIdol,type ManagedWork,type WorkType} from '../stores'

const control='min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm outline-none transition focus:border-red-500 focus:ring-2 focus:ring-red-100'
const roles=['演员','歌手','偶像','主持人','导演','作家','音乐人']
const types:Record<WorkType,string>={movie:'电影',tv:'电视剧',variety:'综艺',book:'书籍',music:'音乐',other:'其他'}
const now=()=>new Date().toISOString()
const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2,7)}`
const toggle=(values:string[],value:string)=>values.includes(value)?values.filter(x=>x!==value):[...values,value]
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-semibold text-slate-700"><span className="mb-2 block">{label}</span>{children}</label>}
function Checks({items,value,onChange}:{items:{id:string;name:string}[];value:string[];onChange:(next:string[])=>void}){return <div className="grid grid-cols-3 gap-2">{items.map(item=><label key={item.id} className={`flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border px-3 text-sm ${value.includes(item.id)?'border-red-400 bg-red-50 text-red-700':'border-slate-200'}`}><input type="checkbox" checked={value.includes(item.id)} onChange={()=>onChange(toggle(value,item.id))}/>{item.name}</label>)}</div>}
function Actions({edit,remove}:{edit:string;remove:()=>void}){return <div className="flex justify-end"><Link to={edit} className="flex h-11 w-11 items-center justify-center text-slate-500 hover:text-blue-600"><Edit3 size={18}/></Link><button onClick={remove} className="flex h-11 w-11 items-center justify-center text-slate-500 hover:text-red-600"><Trash2 size={18}/></button></div>}
function ImageCell({url,name}:{url:string;name:string}){return url?<img src={url} alt={name} className="h-12 w-12 rounded-xl object-cover"/>:<div className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-100 text-slate-400"><Image size={20}/></div>}

export function AdminIdolFormPage(){
 const store=useBasicDataStore(),[params]=useSearchParams(),routeParams=useParams(),edit=store.idols.find(x=>x.id===(routeParams.id||params.get('edit'))),navigate=useNavigate()
 const existingCustom=(edit?.roles||[]).filter(role=>!roles.includes(role))
 const existingCityNames=edit?.cityNames?.length?edit.cityNames:(edit?.cities||[]).map(cityId=>store.cities.find(city=>city.id===cityId)?.name).filter(Boolean) as string[]
 const[form,setForm]=useState(()=>({name:edit?.name||'',avatar:edit?.avatar||'',roles:(edit?.roles||[]).filter(role=>roles.includes(role)),customRole:existingCustom.join('，'),useCustom:existingCustom.length>0,bio:edit?.bio||'',cityText:existingCityNames.join('，'),fanName:edit?.fanName||''}))
 const split=(value:string)=>value.split(/[,，]/).map(item=>item.trim()).filter(Boolean)
 const submit=(e:FormEvent)=>{e.preventDefault();const cityNames=[...new Set(split(form.cityText))],cityIds=cityNames.map(name=>store.cities.find(city=>city.name.toLowerCase()===name.toLowerCase())?.id).filter(Boolean) as string[],customRoles=form.useCustom?split(form.customRole):[],value:ManagedIdol={id:edit?.id||`idol-${id()}`,name:form.name.trim(),avatar:form.avatar.trim(),roles:[...new Set([...form.roles,...customRoles])],bio:form.bio.trim(),cities:cityIds,cityNames,fanName:form.fanName.trim()||undefined,placeCount:edit?.placeCount||0,createdAt:edit?.createdAt||now()};edit?store.updateIdol(edit.id,value):store.addIdol(value);navigate('/admin/idol/list')}
 return <AdminShell title={edit?'编辑爱豆':'录入爱豆'} subtitle="维护地点可关联的爱豆基础资料"><form onSubmit={submit} className="max-w-4xl rounded-2xl bg-white p-8 shadow-sm"><div className="grid grid-cols-2 gap-6"><Field label="爱豆名称 *"><input required className={control} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="头像 URL（选填）"><input className={control} value={form.avatar} onChange={e=>setForm({...form,avatar:e.target.value})}/></Field><div className="col-span-2"><Field label="身份标签"><div className="flex flex-wrap gap-2">{roles.map(role=><label key={role} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-3"><input type="checkbox" checked={form.roles.includes(role)} onChange={()=>setForm({...form,roles:toggle(form.roles,role)})}/>{role}</label>)}<label className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-3"><input type="checkbox" checked={form.useCustom} onChange={()=>setForm({...form,useCustom:!form.useCustom})}/>其他</label></div>{form.useCustom&&<input className={`${control} mt-3`} value={form.customRole} onChange={e=>setForm({...form,customRole:e.target.value})} placeholder="自己填写身份，多个用逗号分隔，例如：舞者、制作人"/>}</Field></div><div className="col-span-2"><Field label="简介"><textarea rows={4} className={`${control} py-3`} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></Field></div><div className="col-span-2"><Field label="关联城市"><input list="city-suggestions" className={control} value={form.cityText} onChange={e=>setForm({...form,cityText:e.target.value})} placeholder="输入或选择城市，多个用逗号分隔，例如：深圳、首尔、东京"/><datalist id="city-suggestions">{store.cities.map(city=><option key={city.id} value={city.name}/>)}</datalist><p className="mt-2 font-normal text-slate-400">会自动识别已有城市；也可以直接填写新城市，不限制数量。</p></Field></div><Field label="粉丝昵称（选填）"><input className={control} value={form.fanName} onChange={e=>setForm({...form,fanName:e.target.value})}/></Field></div><Submit cancel="/admin/idol/list"/></form></AdminShell>
}
export function AdminIdolListPage(){
 const store=useBasicDataStore(),places=useAdminStore(s=>s.records),[query,setQuery]=useState(''),[selected,setSelected]=useState<{id:string;name:string}|null>(null)
 useEffect(()=>recalculateBasicCounts(places),[places])
 const rows=store.idols.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()))
 const count=(idol:ManagedIdol)=>places.filter(place=>place.status==='published'&&((place.relatedIdolIds||[]).includes(idol.id)||(place.relatedIdolNames||place.relatedIdols).includes(idol.name))).length
 return <AdminShell title="爱豆管理" subtitle="搜索、编辑和维护爱豆资料"><Toolbar query={query} setQuery={setQuery} add="/admin/idol" label="录入爱豆"/><Table heads={['头像','名称','身份','关联城市数','关联地点数','操作']}>{rows.map(x=>{const value=count(x);return <tr key={x.id} className="border-t border-slate-100"><td className="px-6 py-4"><ImageCell url={x.avatar} name={x.name}/></td><td className="font-bold">{x.name}</td><td>{x.roles.join('、')||'—'}</td><td>{new Set([...(x.cityNames||[]),...x.cities]).size}</td><td><CountButton value={value} onClick={()=>setSelected({id:x.id,name:x.name})}/></td><td className="pr-6"><Actions edit={`/admin/idol/${x.id}/edit`} remove={()=>confirm(`确定删除“${x.name}”吗？`)&&store.removeIdol(x.id)}/></td></tr>})}</Table>{selected&&<RelationPlacesModal kind="idol" entity={selected} places={places} onClose={()=>setSelected(null)}/>}</AdminShell>
}

export function AdminWorkFormPage(){
 const store=useBasicDataStore(),[params]=useSearchParams(),edit=store.works.find(x=>x.id===params.get('edit')),navigate=useNavigate()
 const[form,setForm]=useState(()=>({name:edit?.name||'',type:edit?.type||'movie' as WorkType,year:edit?.year?String(edit.year):'',region:edit?.region||'',cover:edit?.cover||'',quote:edit?.quote||'',relatedIdolIds:edit?.relatedIdolIds||[],relatedCities:edit?.relatedCities||[]}))
 const submit=(e:FormEvent)=>{e.preventDefault();const value:ManagedWork={id:edit?.id||`work-${id()}`,name:form.name.trim(),type:form.type,year:form.year?Number(form.year):undefined,region:form.region.trim()||undefined,cover:form.cover.trim(),quote:form.quote.trim(),relatedIdolIds:form.relatedIdolIds,relatedCities:form.relatedCities,placeCount:edit?.placeCount||0,createdAt:edit?.createdAt||now()};edit?store.updateWork(edit.id,value):store.addWork(value);navigate('/admin/work/list')}
 return <AdminShell title={edit?'编辑作品':'录入作品'} subtitle="维护电影、剧集、综艺、书籍与音乐资料"><form onSubmit={submit} className="max-w-4xl rounded-2xl bg-white p-8 shadow-sm"><div className="grid grid-cols-2 gap-6"><Field label="作品名称 *"><input required className={control} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="类型 *"><select required className={control} value={form.type} onChange={e=>setForm({...form,type:e.target.value as WorkType})}>{Object.entries(types).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field><Field label="年份（选填）"><input type="number" min="1800" max="2100" className={control} value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></Field><Field label="地区（选填）"><input className={control} value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></Field><div className="col-span-2"><Field label="封面 URL（选填）"><input className={control} value={form.cover} onChange={e=>setForm({...form,cover:e.target.value})}/></Field></div><div className="col-span-2"><Field label="一句话简介 *"><input required className={control} value={form.quote} onChange={e=>setForm({...form,quote:e.target.value})}/></Field></div><div className="col-span-2"><Field label="关联爱豆"><Checks items={store.idols} value={form.relatedIdolIds} onChange={relatedIdolIds=>setForm({...form,relatedIdolIds})}/></Field></div><div className="col-span-2"><Field label="关联城市"><Checks items={store.cities} value={form.relatedCities} onChange={relatedCities=>setForm({...form,relatedCities})}/></Field></div></div><Submit cancel="/admin/work/list"/></form></AdminShell>
}
export function AdminWorkListPage(){
 const store=useBasicDataStore(),places=useAdminStore(s=>s.records),[selected,setSelected]=useState<{id:string;name:string}|null>(null)
 useEffect(()=>recalculateBasicCounts(places),[places])
 const count=(work:ManagedWork)=>places.filter(place=>place.status==='published'&&[...place.relatedMovies,...place.relatedVariety,...place.relatedTV,...(place.relatedOtherWorks||[])].includes(work.name)).length
 return <AdminShell title="作品管理" subtitle="维护地点可关联的作品资料"><Toolbar add="/admin/work" label="录入作品"/><Table heads={['封面','名称','类型','年份','关联爱豆','关联地点数','操作']}>{store.works.map(x=><tr key={x.id} className="border-t border-slate-100"><td className="px-6 py-4"><ImageCell url={x.cover} name={x.name}/></td><td className="font-bold">{x.name}</td><td>{types[x.type]}</td><td>{x.year||'—'}</td><td>{x.relatedIdolIds.map(id=>store.idols.find(i=>i.id===id)?.name).filter(Boolean).join('、')||'—'}</td><td><CountButton value={count(x)} onClick={()=>setSelected({id:x.id,name:x.name})}/></td><td className="pr-6"><Actions edit={`/admin/work?edit=${x.id}`} remove={()=>confirm(`确定删除“${x.name}”吗？`)&&store.removeWork(x.id)}/></td></tr>)}</Table>{selected&&<RelationPlacesModal kind="work" entity={selected} places={places} onClose={()=>setSelected(null)}/>}</AdminShell>
}

export function AdminCityFormPage(){
 const store=useBasicDataStore(),[params]=useSearchParams(),edit=store.cities.find(x=>x.id===params.get('edit')),navigate=useNavigate()
 const[form,setForm]=useState(()=>({name:edit?.name||'',region:edit?.region||'',cover:edit?.cover||'',story:edit?.story||'',iconUrl:edit?.iconUrl||''}))
 const submit=(e:FormEvent)=>{e.preventDefault();const value:ManagedCity={id:edit?.id||`city-${id()}`,...form,name:form.name.trim(),region:form.region.trim(),cover:form.cover.trim(),story:form.story.trim(),iconUrl:form.iconUrl.trim(),placeCount:edit?.placeCount||0,routeCount:edit?.routeCount||0,createdAt:edit?.createdAt||now()};edit?store.updateCity(edit.id,value):store.addCity(value);navigate('/admin/city/list')}
 return <AdminShell title={edit?'编辑城市':'录入城市'} subtitle="维护城市资料与首页展示素材"><form onSubmit={submit} className="max-w-4xl rounded-2xl bg-white p-8 shadow-sm"><div className="grid grid-cols-2 gap-6"><Field label="城市名称 *"><input required className={control} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="所属省份 / 国家 *"><input required className={control} value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></Field><div className="col-span-2"><Field label="城市封面图 URL（选填）"><input className={control} value={form.cover} onChange={e=>setForm({...form,cover:e.target.value})}/></Field></div><div className="col-span-2"><Field label="城市故事 / 简介"><textarea rows={5} className={`${control} py-3`} value={form.story} onChange={e=>setForm({...form,story:e.target.value})}/></Field></div><div className="col-span-2"><Field label="地标线描图标 URL（选填）"><input className={control} value={form.iconUrl} onChange={e=>setForm({...form,iconUrl:e.target.value})}/></Field></div></div><Submit cancel="/admin/city/list"/></form></AdminShell>
}
export function AdminCityListPage(){
 const store=useBasicDataStore(),places=useAdminStore(s=>s.records),[selected,setSelected]=useState<{id:string;name:string}|null>(null)
 useEffect(()=>recalculateBasicCounts(places),[places])
 const count=(city:ManagedCity)=>places.filter(place=>place.status==='published'&&place.city===city.name).length
 return <AdminShell title="城市管理" subtitle="维护城市、封面和首页地标素材"><Toolbar add="/admin/city" label="录入城市"/><Table heads={['封面','名称','地点数','路线数','操作']}>{store.cities.map(x=><tr key={x.id} className="border-t border-slate-100"><td className="px-6 py-4"><ImageCell url={x.cover} name={x.name}/></td><td className="font-bold">{x.name}<small className="ml-2 font-normal text-slate-400">{x.region}</small></td><td><CountButton value={count(x)} onClick={()=>setSelected({id:x.id,name:x.name})}/></td><td>{x.routeCount}</td><td className="pr-6"><Actions edit={`/admin/city?edit=${x.id}`} remove={()=>confirm(`确定删除“${x.name}”吗？`)&&store.removeCity(x.id)}/></td></tr>)}</Table>{selected&&<RelationPlacesModal kind="city" entity={selected} places={places} onClose={()=>setSelected(null)}/>}</AdminShell>
}

function CountButton({value,onClick}:{value:number;onClick:()=>void}){return value>0?<button onClick={onClick} className="min-h-10 font-bold text-blue-600 underline decoration-blue-300 underline-offset-4 hover:text-blue-800">{value}</button>:<span className="text-slate-400">0</span>}
function RelationPlacesModal({kind,entity,places,onClose}:{kind:'idol'|'work'|'city';entity:{id:string;name:string};places:AdminPlace[];onClose:()=>void}){
 const update=useAdminStore(s=>s.updateRecord)
 const rows=places.filter(place=>kind==='idol'?((place.relatedIdolIds||[]).includes(entity.id)||(place.relatedIdolNames||place.relatedIdols).includes(entity.name)):kind==='work'?[...place.relatedMovies,...place.relatedVariety,...place.relatedTV,...(place.relatedOtherWorks||[])].includes(entity.name):place.city===entity.name)
 const removeRelation=(place:AdminPlace)=>{if(!confirm(`确定移除该地点与 ${entity.name} 的关联？地点本身不会被删除`))return;const changes={relatedIdols:place.relatedIdols.filter(name=>name!==entity.name),relatedIdolNames:(place.relatedIdolNames||place.relatedIdols).filter(name=>name!==entity.name),relatedIdolIds:(place.relatedIdolIds||[]).filter(id=>id!==entity.id)};update(place.id,changes);setTimeout(()=>recalculateBasicCounts(useAdminStore.getState().records),0)}
 const relationNames:Record<string,string>={same_style:'同款',filming:'节目取景',public_event:'公开活动',personal_share:'个人分享',other:'其他'}
 return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/55" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="h-full w-[820px] overflow-y-auto bg-white p-8 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">关联地点详情</p><h2 className="mt-1 text-2xl font-black">{entity.name} 的关联地点（{rows.length}个）</h2></div><button onClick={onClose} className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100"><X/></button></div><div className="mt-7 overflow-x-auto rounded-xl border"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">地点名称</th><th>城市</th><th>地址</th><th>关系类型</th><th>可信度</th><th>状态</th><th className="pr-4 text-right">操作</th></tr></thead><tbody>{rows.map(place=><tr key={place.id} className="border-t"><td className="px-4 py-4 font-bold">{place.name}</td><td>{place.city}</td><td className="max-w-52 truncate pr-4">{place.address}</td><td>{relationNames[place.relationType]||place.relationType}</td><td>{place.credibility||'待审核'}</td><td>{place.status==='published'?'已发布':place.status==='rejected'?'已驳回':'待审核'}</td><td className="pr-4"><div className="flex justify-end gap-2"><Link to={`/place/${place.id}`} target="_blank" className="flex min-h-10 items-center gap-1 rounded-lg border px-3 text-xs"><ExternalLink size={14}/>查看</Link><Link to={`/admin/content?edit=${place.id}`} className="flex min-h-10 items-center gap-1 rounded-lg border px-3 text-xs"><Edit3 size={14}/>编辑</Link>{kind==='idol'&&<button onClick={()=>removeRelation(place)} className="min-h-10 rounded-lg border border-red-200 px-3 text-xs text-red-600">移除关联</button>}</div></td></tr>)}</tbody></table>{!rows.length&&<div className="py-16 text-center text-slate-400">暂无关联地点</div>}</div></aside></div>
}
function Submit({cancel}:{cancel:string}){return <div className="mt-8 flex justify-end gap-3"><Link to={cancel} className="flex min-h-12 items-center rounded-xl border border-slate-300 px-6 font-semibold">取消</Link><button className="min-h-12 rounded-xl bg-slate-950 px-8 font-bold text-white">保存</button></div>}
function Toolbar({query,setQuery,add,label}:{query?:string;setQuery?:(v:string)=>void;add:string;label:string}){return <div className="mb-6 flex justify-between rounded-2xl bg-white p-5 shadow-sm">{setQuery?<label className="flex min-h-12 w-96 items-center gap-3 rounded-xl border border-slate-300 px-4"><Search size={18}/><input className="w-full outline-none" value={query} onChange={e=>setQuery(e.target.value)} placeholder="按名称搜索"/></label>:<span/>}<Link to={add} className="flex min-h-12 items-center gap-2 rounded-xl bg-red-600 px-5 font-bold text-white"><Plus size={18}/>{label}</Link></div>}
function Table({heads,children}:{heads:string[];children:React.ReactNode}){return <div className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{heads.map((x,i)=><th key={x} className={`${i===0?'px-6 py-4':''} ${i===heads.length-1?'pr-6 text-right':''}`}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
