import {Heart,MapPin,Share2} from 'lucide-react'
import {Link,useParams} from 'react-router-dom'
import {BottomNav,Card,Header} from '../components/ui'
import {places} from '../data/mock'
import {useAdminStore,useBasicDataStore} from '../stores'
export function CityPage(){
 const{id}=useParams(),cities=useBasicDataStore(s=>s.cities),city=cities.find(x=>x.id===id)||cities[0],allRecords=useAdminStore(s=>s.records),records=allRecords.filter(x=>x.status==='published'),list=records.filter(x=>x.city===city?.name)
 if(!city)return <Header title="城市不存在" back/>
 const image=city.cover||places[0].images[0]
 return <main className="min-h-[100dvh] bg-paper pb-28"><Header title="城市详情" back action={<div className="flex gap-2"><button className="h-11 w-11 rounded-full bg-white"><Share2 className="mx-auto"/></button><button className="h-11 w-11 rounded-full bg-white"><Heart className="mx-auto"/></button></div>}/><section className="px-5"><div className="relative h-72 overflow-hidden rounded-[28px]"><img src={image} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><h1 className="text-4xl font-black">{city.name} <span className="text-yellow-300">✦</span></h1><p className="mt-2">中国 · {city.region}</p><p className="mt-4 flex items-center gap-1 text-sm"><MapPin size={16}/>关联地点 {Math.max(28,list.length)} 个</p></div></div>
 <Card className="mt-4 p-5"><h2 className="font-black">城市故事</h2><p className="mt-3 text-lg font-bold text-orange-500">“ 一座连接海洋与未来的城市</p><p className="mt-3 text-sm leading-7 text-stone-500">{city.story||'从渔村到创新之都，这座城市有海风、落日、公园、街区，也有无数动人的故事。'}</p></Card>
 <h2 className="mb-3 mt-7 text-lg font-black">关联内容</h2><div className="grid grid-cols-2 gap-3"><Card className="p-4"><b>相关作品</b><p className="mt-2 text-2xl font-black">18</p><div className="mt-3 flex -space-x-2">{places.slice(0,3).map(x=><img key={x.id} src={x.images[0]} className="h-10 w-10 rounded-lg border-2 border-white object-cover"/>)}</div></Card><Card className="p-4"><b>相关人物 / 活动</b><p className="mt-2 text-2xl font-black">12</p><p className="mt-3 text-sm text-stone-400">公开活动 · 城市足迹</p></Card></div>
 <Title text="热门地点"/><div className="flex gap-3 overflow-x-auto">{[...list.map(x=>({id:x.id,name:x.name,img:x.images[0]})),...places.map(x=>({id:x.id,name:x.name,img:x.images[0]}))].slice(0,4).map((x,i)=><Link to={`/place/${x.id}`} key={x.id} className="w-36 shrink-0 rounded-[20px] bg-white p-2 shadow-soft"><img src={x.img} className="h-20 w-full rounded-2xl object-cover"/><b className="mt-2 block truncate text-sm">{x.name}</b><p className="text-[11px] text-stone-400">步行 {8+i*2} 分钟</p></Link>)}</div><Title text="推荐路线"/><Card className="p-4"><b>{city.name}湾日落路线</b><p className="mt-2 text-xs text-stone-400">3小时 · 4个地点</p><p className="mt-3 text-sm">城市公园 → 人才公园 → 海滨步道</p></Card><button className="mt-7 min-h-14 w-full rounded-full bg-orange-500 font-black text-white">✦ 开始探索{city.name}</button></section><BottomNav/></main>
}
function Title({text}:{text:string}){return <div className="mb-3 mt-7 flex justify-between"><h2 className="text-lg font-black">{text}</h2><span className="text-xs text-stone-400">全部 ›</span></div>}
