import {ArrowLeft,CheckCircle2,MessageSquareText,Send} from 'lucide-react'
import {FormEvent,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {useFeedbackStore,type FeedbackType} from '../stores'
const control='min-h-12 w-full rounded-2xl border border-stone-200 bg-white px-4 outline-none focus:border-orange-400 focus:ring-2 focus:ring-orange-100'
export function FeedbackPage(){
 const add=useFeedbackStore(s=>s.add),navigate=useNavigate(),[type,setType]=useState<FeedbackType>('suggestion'),[content,setContent]=useState(''),[contact,setContact]=useState(''),[sent,setSent]=useState(false),[submitting,setSubmitting]=useState(false)
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!content.trim()||submitting)return;setSubmitting(true);const saved=await add({id:`feedback-${Date.now()}`,type,content:content.trim(),contact:contact.trim()||undefined,status:'unread',createdAt:new Date().toISOString()});setSubmitting(false);if(!saved)return;setSent(true);setTimeout(()=>navigate('/profile'),900)}
 return <main className="min-h-[100dvh] bg-paper px-5 pb-10"><header className="flex h-16 items-center"><Link to="/profile" className="flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-soft"><ArrowLeft/></Link><h1 className="mx-auto pr-11 font-black">意见反馈</h1></header>{sent?<div className="mt-24 text-center"><CheckCircle2 className="mx-auto text-emerald-500" size={54}/><h2 className="mt-5 text-2xl font-black">感谢你的反馈</h2><p className="mt-2 text-sm text-stone-500">反馈已经安全保存到云端。</p></div>:<form onSubmit={submit} className="mt-5 rounded-[26px] bg-white p-6 shadow-soft"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-50 text-orange-500"><MessageSquareText/></span><div><h2 className="font-black">告诉我们你的想法</h2><p className="text-xs text-stone-400">每一条反馈都会帮助循迹变得更好</p></div></div><label className="mt-7 block text-sm font-bold">反馈类型</label><div className="mt-3 grid grid-cols-3 gap-2">{([['bug','Bug'],['suggestion','建议'],['correction','内容纠错']] as const).map(([value,label])=><button type="button" key={value} onClick={()=>setType(value)} className={`min-h-11 rounded-full text-xs font-bold ${type===value?'bg-stone-900 text-white':'bg-stone-100 text-stone-500'}`}>{label}</button>)}</div><label className="mt-6 block text-sm font-bold">反馈内容 *</label><textarea required minLength={5} rows={7} value={content} onChange={e=>setContent(e.target.value)} className={`${control} mt-2 resize-none py-3`} placeholder="请描述你遇到的问题、建议或需要纠正的内容"/><label className="mt-6 block text-sm font-bold">联系方式（选填）</label><input value={contact} onChange={e=>setContact(e.target.value)} className={`${control} mt-2`} placeholder="手机号、邮箱或其他联系方式"/><button disabled={submitting} className="mt-7 flex min-h-14 w-full items-center justify-center gap-2 rounded-full bg-orange-500 font-black text-white active:scale-[.98] disabled:opacity-60"><Send size={18}/>{submitting?'正在保存到云端…':'提交反馈'}</button></form>}</main>
}
