import {MapPin,MoreHorizontal} from 'lucide-react'
import {useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {BottomNav,Card,Header,relationLabel} from '../components/ui'
import {getIdol,idols as mockIdols,places as mockPlaces,relations} from '../data/mock'
import {useAdminStore,useBasicDataStore} from '../stores'
import {trackEvent} from '../services/analytics'
export function IdolPage(){
 const{ id:raw='' }=useParams(),param=decodeURIComponent(raw),basic=useBasicDataStore(),managed=basic.idols.find(x=>x.id===param||x.name===param),mock=getIdol(param)||mockIdols.find(x=>x.name===param),allRecords=useAdminStore(s=>s.records),name=managed?.name||mock?.name||param
 const records=allRecords.filter(x=>x.status==='published'&&(x.relatedIdolNames||x.relatedIdols).includes(name)),mockRelated=relations.filter(x=>x.idolId===mock?.id).map(r=>({place:mockPlaces.find(p=>p.id===r.placeId)!,type:r.relationType})),[expanded,setExpanded]=useState(false)
 useEffect(()=>trackEvent({type:'page_view',page:'idol_detail'}),[name])
 if(!name)return <Header title="未找到爱豆" back/>
 const cities=new Set(records.map(x=>x.city)),avatar=managed?.avatar||mock?.avatar||'',bio=managed?.bio||mock?.bio||'',roles=managed?.roles||[],needsProfile=!avatar||!bio||roles.length===0,initials=name.slice(0,2)
 const cards=records.length?records.map(x=>({id:x.id,name:x.name,city:x.city,address:x.address,image:x.images[0],type:x.relationType})):mockRelated.map(({place,type})=>({id:place.id,name:place.name,city:'深圳',address:place.address,image:place.images[0],type}))
 return <main className="min-h-[100dvh] bg-paper pb-28"><Header title="明星主页" back action={<button className="flex h-11 w-11 items-center justify-center rounded-full bg-white"><MoreHorizontal/></button>}/><section className="px-5"><div className="relative h-64 overflow-hidden rounded-[28px] bg-gradient-to-br from-orange-50 via-amber-100 to-orange-200">{avatar?<img src={avatar} alt={name} className="absolute inset-0 h-full w-full object-cover object-[center_22%]"/>:<div className="absolute inset-0 flex items-center justify-end bg-gradient-to-br from-orange-50 via-amber-100 to-orange-200 pr-9 text-6xl font-black text-orange-400/70">{initials}</div>}<div className="absolute inset-0 bg-gradient-to-r from-[#fff0b8]/95 via-[#fff0b8]/55 to-black/5"/><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-black/25 to-transparent"/><div className="relative z-10 flex h-full max-w-[68%] flex-col justify-end p-6 pb-7"><h1 className="text-4xl font-black text-stone-950 drop-shadow-sm">{name} <span className="text-xl text-[#eaa916]">✦</span></h1><p className="mt-2 text-sm font-medium text-stone-700">{roles.length?roles.join(' · '):'资料待补充'}</p><span className="mt-4 w-fit rounded-full bg-white/80 px-3 py-1 text-xs text-stone-800 shadow-sm backdrop-blur-sm">公开关联地点 {cards.length} 个</span></div></div>
 <Card className="-mt-1 grid grid-cols-4 divide-x p-4 text-center"><Stat value={String(cities.size||managed?.cities.length||1)} label="关联城市"/><Stat value={String(cards.length)} label="关联地点"/><Stat value={String(Math.ceil(cards.length/3))} label="同款路线"/><Stat value="—" label="粉丝收藏"/></Card>
 {needsProfile&&<div className="mt-5 rounded-[20px] border border-dashed border-orange-300 bg-orange-50 p-4 text-sm text-orange-700"><b>资料待补充</b><p className="mt-1 text-xs">头像、身份标签和个人简介可由管理员后续完善。</p></div>}
 <section className="mt-7"><h2 className="mb-3 text-lg font-black">关于他</h2><Card className="p-5"><p className={`text-sm leading-7 text-stone-600 ${expanded?'':'line-clamp-3'}`}>{bio||`“${name}”的公开资料正在整理中。这里会汇总与其有关的公开活动、同款地点和作品足迹。`}</p>{bio&&<button onClick={()=>setExpanded(x=>!x)} className="mt-2 float-right text-xs text-stone-500">{expanded?'收起':'展开'}⌄</button>}<div className="clear-both"/></Card></section>
 <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black">关联地点</h2><span className="text-xs text-stone-400">{cards.length} 个</span></div><div className="space-y-3">{cards.map(card=><Link to={`/place/${card.id}`} key={card.id} className="grid grid-cols-[88px_1fr] gap-3 rounded-[20px] bg-white p-3 shadow-soft active:scale-[.99]"><div className="flex h-24 w-22 items-center justify-center overflow-hidden rounded-2xl bg-gradient-to-br from-orange-100 to-amber-200">{card.image?<img src={card.image} className="h-full w-full object-cover"/>:<MapPin className="text-orange-400"/>}</div><div className="py-1"><b>{card.name}</b><p className="mt-2 text-xs text-stone-400">{card.city} · {card.address}</p><span className="mt-3 inline-block rounded-full bg-orange-50 px-2.5 py-1 text-[10px] text-orange-600">{relationLabel[card.type as keyof typeof relationLabel]||'公开关联'}</span></div></Link>)}{!cards.length&&<Card className="p-10 text-center text-sm text-stone-400">暂时没有已发布的关联地点</Card>}</div></section></section><BottomNav/></main>
}
function Stat({value,label}:{value:string;label:string}){return <div><b className="text-xl">{value}</b><p className="mt-1 text-[10px] text-stone-400">{label}</p></div>}
