import {ChevronDown,ChevronUp,LocateFixed,MapPin,Search} from 'lucide-react'
import {useEffect,useMemo,useRef,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {BottomNav,CredibilityBadge} from '../components/ui'
import {initMap} from '../hooks/useAMap'
import {useAdminStore,type AdminPlace} from '../stores'

type Location={lng:number;lat:number}
type Nearby=AdminPlace&{distance:number}
const SHENZHEN:Location={lng:114.0579,lat:22.5431}
const colors:Record<string,string>={same_style:'#f59e0b',filming:'#3b82f6',public_event:'#16a34a',personal_share:'#ec4899',other:'#78716c'}
const haversine=(a:Location,b:Location)=>{const r=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
export function MapExplorePage(){
 const records=useAdminStore(s=>s.records),places=useMemo(()=>records.filter(p=>p.status==='published'),[records]),navigate=useNavigate(),container=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),amapRef=useRef<any>(null)
 const[user,setUser]=useState<Location>(SHENZHEN),[notice,setNotice]=useState('正在获取你的位置…'),[expanded,setExpanded]=useState(true),[selected,setSelected]=useState<string>(),[filters,setFilters]=useState<string[]>(['地点']),[query,setQuery]=useState(''),[mapError,setMapError]=useState('')
 const nearby=useMemo(()=>places.map(p=>({...p,distance:haversine(user,{lng:p.lng,lat:p.lat})})).filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.distance-b.distance),[places,user,query])
 const locate=()=>{if(!navigator.geolocation){setNotice('浏览器不支持定位，已显示深圳默认区域');setUser(SHENZHEN);return}setNotice('正在获取你的位置…');navigator.geolocation.getCurrentPosition(pos=>{const next={lng:pos.coords.longitude,lat:pos.coords.latitude};setUser(next);setNotice('已定位到你的位置');mapRef.current?.setZoomAndCenter(14,[next.lng,next.lat])},error=>{setUser(SHENZHEN);const message=error.code===error.PERMISSION_DENIED?'定位权限未开启：请在地址栏左侧的网站设置中允许位置权限，再点右侧定位按钮。':error.code===error.TIMEOUT?'定位超时，已显示深圳默认区域；请检查网络后重试。':'当前设备无法提供定位，已显示深圳默认区域。';setNotice(message)},{enableHighAccuracy:false,timeout:15000,maximumAge:300000})}
 useEffect(()=>{locate()},[])
 useEffect(()=>{let cancelled=false;if(!container.current)return;initMap(container.current,{center:[user.lng,user.lat],zoom:13}).then(({AMap,map})=>{if(cancelled)return;amapRef.current=AMap;mapRef.current=map;new AMap.Marker({map,position:[user.lng,user.lat],content:'<div style="width:18px;height:18px;border-radius:50%;background:#2f80ed;border:4px solid white;box-shadow:0 0 0 6px rgba(47,128,237,.22)"></div>',offset:new AMap.Pixel(-9,-9)});places.forEach(p=>{const color=colors[p.relationType]||colors.other;const marker=new AMap.Marker({map,position:[p.lng,p.lat],title:p.name,content:`<div style="transform:translate(-50%,-100%);white-space:nowrap"><div style="display:inline-flex;align-items:center;gap:4px;padding:7px 10px;border-radius:14px;background:${color};color:white;font-size:11px;font-weight:700;box-shadow:0 5px 18px rgba(0,0,0,.2)">● ${p.name}</div></div>`});marker.on('click',()=>{setSelected(p.id);map.setZoomAndCenter(15,[p.lng,p.lat]);const info=new AMap.InfoWindow({offset:new AMap.Pixel(0,-34),content:`<div style="min-width:170px;padding:8px"><b>${p.name}</b><p style="margin:7px 0;color:#777;font-size:12px">${haversine(user,{lng:p.lng,lat:p.lat}).toFixed(1)} km · 可信度 ${p.credibility||'C'}</p><a href="/place/${p.id}" style="color:#e97925;font-size:12px;font-weight:700">查看详情 →</a></div>`});info.open(map,[p.lng,p.lat])})})}).catch(error=>setMapError(error instanceof Error?error.message:'地图加载失败'));return()=>{cancelled=true;mapRef.current?.clearMap?.();mapRef.current=null}},[places])
 const focus=(p:Nearby)=>{setSelected(p.id);mapRef.current?.setZoomAndCenter(16,[p.lng,p.lat])}
 return <main className="relative h-[100dvh] overflow-hidden bg-[#e8e5de]"><div ref={container} className="absolute inset-0 bottom-16"/>{mapError&&<div className="absolute inset-0 bottom-16 bg-[#e8e5de]" style={{backgroundImage:'linear-gradient(#d8d3ca 1px,transparent 1px),linear-gradient(90deg,#d8d3ca 1px,transparent 1px)',backgroundSize:'36px 36px'}}>{places.map((p,i)=><button key={p.id} onClick={()=>focus({...p,distance:0})} className="absolute rounded-full px-3 py-2 text-[10px] font-bold text-white shadow-lg" style={{left:`${12+(i*23)%72}%`,top:`${28+(i*17)%35}%`,background:colors[p.relationType]}}>{p.name}</button>)}</div>}
 <div className="absolute inset-x-0 top-0 z-20 bg-gradient-to-b from-paper via-paper/85 to-transparent px-5 pb-8 pt-5"><div className="flex items-center gap-3"><button onClick={()=>navigate(-1)} className="flex h-12 w-12 items-center justify-center rounded-full bg-white shadow-soft">←</button><label className="flex min-h-14 flex-1 items-center gap-3 rounded-[20px] bg-white px-4 shadow-soft"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索 Idol / 作品 / 地点 / 城市" className="w-full bg-transparent text-sm outline-none"/></label></div><div className="mt-3 flex gap-2 pl-14">{['爱豆','作品','地点'].map(x=><button key={x} onClick={()=>setFilters(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x])} className={`min-h-10 rounded-full px-4 text-xs font-bold shadow-sm ${filters.includes(x)?'bg-stone-900 text-white':'bg-white text-stone-500'}`}>{x}</button>)}</div><p className="mt-2 pl-14 text-[11px] text-stone-500">{notice}{mapError&&` · 地图暂不可用：${mapError}`}</p></div>
 <button onClick={locate} className="absolute bottom-[285px] right-5 z-20 flex h-12 w-12 items-center justify-center rounded-full bg-white shadow-lg active:scale-95"><LocateFixed/></button>
 <section className={`absolute inset-x-0 bottom-[64px] z-30 rounded-t-[28px] bg-paper/95 shadow-[0_-12px_40px_rgba(70,50,30,.14)] backdrop-blur-xl transition-all ${expanded?'h-64':'h-20'}`}><button onClick={()=>setExpanded(x=>!x)} className="flex min-h-16 w-full items-center justify-between px-5"><div className="text-left"><b>附近地点</b><p className="text-[11px] text-stone-400">{nearby.length} 个已发布地点 · 按距离排序</p></div>{expanded?<ChevronDown/>:<ChevronUp/>}</button>{expanded&&<div className="h-[190px] overflow-y-auto px-4 pb-4">{nearby.map(p=><button key={p.id} onClick={()=>focus(p)} className={`mb-2 grid min-h-20 w-full grid-cols-[56px_1fr_auto] items-center gap-3 rounded-[18px] p-2 text-left ${selected===p.id?'bg-orange-50 ring-2 ring-orange-300':'bg-white'}`}><img src={p.images[0]||''} className="h-14 w-14 rounded-2xl bg-stone-100 object-cover"/><div><b className="text-sm">{p.name}</b><p className="mt-1 flex items-center gap-1 text-[11px] text-stone-400"><MapPin size={12}/>{p.distance<1?`${Math.round(p.distance*1000)} m`:`${p.distance.toFixed(1)} km`}</p></div><CredibilityBadge level={p.credibility||'C'}/></button>)}{!nearby.length&&<p className="py-10 text-center text-sm text-stone-400">暂无已发布的附近地点</p>}</div>}</section><BottomNav/></main>
}
