import {Camera,ChevronRight,Clock,Clapperboard,MapPin,Route,Star,UserRound} from 'lucide-react'
import {Link,useParams} from 'react-router-dom'
import {useEffect} from 'react'
import {BottomNav,Card,CredibilityBadge,Header,PageAction,relationLabel} from '../components/ui'
import {getIdol,getPlace,getWork,places,relations} from '../data/mock'
import {toPublicPlace,toPublicRelation} from '../data/adminAdapters'
import {useAdminStore,useFavoriteStore,useRouteStore} from '../stores'
import {trackEvent} from '../services/analytics'
export function PlacePage(){
 const{id}=useParams(),record=useAdminStore(s=>s.records.find(x=>x.id===id&&x.status==='published')),place=record?toPublicPlace(record):getPlace(id),rel=record?toPublicRelation(record):relations.find(x=>x.placeId===id),toggle=useFavoriteStore(s=>s.toggle),fav=useFavoriteStore(s=>s.placeIds.includes(id||'')),add=useRouteStore(s=>s.add)
 useEffect(()=>{if(place)trackEvent({type:'page_view',page:'place_detail',placeId:place.id})},[place?.id])
 if(!place||!rel)return <Header title="地点不存在" back/>
 const idol=record?.relatedIdols[0]||getIdol(rel.idolId)?.name||'循迹公开活动',work=record?.relatedMovies[0]||record?.relatedTV[0]||record?.relatedVariety[0]||getWork(rel.workId)?.name
 return <main className="min-h-[100dvh] bg-paper pb-36"><Header title="地点详情" back action={<PageAction active={fav} onClick={()=>toggle(place.id)}/>}/><section className="px-5"><div className="relative"><img src={place.images[0]} className="h-[330px] w-full rounded-[28px] object-cover"/><div className="absolute -bottom-5 right-4 flex h-24 w-32 items-center justify-center rounded-[20px] border-4 border-white bg-[#eee9df] shadow-soft"><MapPin className="text-orange-500" size={30}/></div></div>
 <Card className="-mt-2 p-6 pt-7"><h1 className="text-3xl font-black">{place.name}</h1><div className="mt-3 flex flex-wrap items-center gap-3 text-sm text-stone-500"><span>{place.city||'深圳'} · {place.address.slice(0,8)}</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">可到访</span><span className="flex items-center gap-1"><Clock size={15}/>推荐停留 45分钟</span></div><p className="mt-4 text-sm leading-6 text-stone-600">{record?.relationDesc||'城市记忆与公开足迹交汇的地点，适合加入一段慢行路线。'}</p></Card>
 <Block title="关联内容"><Card className="overflow-hidden"><Row icon={<Clapperboard/>} label="关联作品" value={work||'暂无关联作品'}/><Row icon={<UserRound/>} label="关联 Idol / 活动" value={idol}/><div className="grid grid-cols-3 border-t p-4 text-center"><Info label="关系类型"><span className="rounded-lg bg-orange-50 px-2 py-1 text-xs text-orange-700">{relationLabel[rel.relationType]}</span></Info><Info label="证据来源"><span className="text-xs">公开资料<br/>媒体记录</span></Info><Info label="可信度等级"><b className="text-3xl text-orange-500">{rel.credibility}</b><CredibilityBadge level={rel.credibility}/></Info></div></Card></Block>
 <Block title="☆ 为什么值得去"><Card className="space-y-4 p-5">{['作品氛围高度贴合，可感受真实场景','位置便利，可串联附近多处地点','证据来源公开透明，适合放心加入路线'].map((x,i)=><p key={x} className="flex gap-3 text-sm"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-orange-50 text-orange-500">{[<Camera/>,<MapPin/>,<Star/>][i]}</span>{x}</p>)}</Card></Block>
 {(place.transportGuide||place.coreSpots||place.tips)&&<Block title="攻略信息"><Card className="space-y-4 p-5">{place.transportGuide&&<Guide title="怎么去" text={place.transportGuide}/>} {place.coreSpots&&<Guide title="打卡路线" text={place.coreSpots}/>} {place.tips&&<Guide title="小贴士" text={place.tips}/>}</Card></Block>}
 <Block title="⌖ 附近地点推荐"><div className="flex gap-3 overflow-x-auto">{places.filter(x=>x.id!==place.id).slice(0,4).map((x,i)=><Link to={`/place/${x.id}`} key={x.id} className="w-36 shrink-0 rounded-[20px] bg-white p-2 shadow-soft"><img src={x.images[0]} className="h-20 w-full rounded-2xl object-cover"/><b className="mt-2 block truncate text-sm">{x.name}</b><p className="text-[11px] text-stone-400">步行 {8+i*3} 分钟</p></Link>)}</div></Block></section>
 <div className="fixed bottom-[72px] left-1/2 z-30 grid w-full max-w-md -translate-x-1/2 grid-cols-[1.1fr_1fr] gap-3 bg-paper/95 px-5 py-3 backdrop-blur"><button onClick={()=>add(place.id)} className="flex min-h-14 items-center justify-center gap-2 rounded-full bg-orange-500 font-bold text-white active:scale-95"><Route/>加入路线</button><button className="min-h-14 rounded-full border border-stone-300 bg-white font-bold active:scale-95">补充证据 / 纠错</button></div><BottomNav/></main>
}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-7"><h2 className="mb-3 text-lg font-black">{title}</h2>{children}</section>}
function Row({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="grid min-h-16 grid-cols-[28px_105px_1fr_20px] items-center gap-2 border-b px-4 text-sm"><span>{icon}</span><span className="text-stone-500">{label}</span><b className="truncate">{value}</b><ChevronRight size={17}/></div>}
function Info({label,children}:{label:string;children:React.ReactNode}){return <div className="flex min-h-20 flex-col items-center justify-between border-r last:border-0"><span className="text-[11px] text-stone-400">{label}</span>{children}</div>}
function Guide({title,text}:{title:string;text:string}){return <div><b>{title}</b><p className="mt-1 whitespace-pre-line text-sm leading-6 text-stone-500">{text}</p></div>}
