import {ChevronRight,Heart,LogIn,MapPin,MessageSquareText,MessageSquareWarning,Settings,Star,UserMinus} from 'lucide-react'
import {useState} from 'react'
import {Link} from 'react-router-dom'
import {BottomNav,EmptyState,Header} from '../components/ui'
import {idols,places} from '../data/mock'
import {useBasicDataStore,useFavoriteStore,useFollowingStore,useRouteStore} from '../stores'
export function ProfilePage(){const[logged,setLogged]=useState(false);const favs=useFavoriteStore(s=>s.placeIds),route=useRouteStore(s=>s.placeIds),followedIds=useFollowingStore(s=>s.idolIds),unfollow=useFollowingStore(s=>s.unfollow),managedIdols=useBasicDataStore(s=>s.idols),followedIdols=managedIdols.filter(idol=>followedIds.includes(idol.id));return <main className="min-h-[100dvh] bg-paper pb-24"><Header title="个人中心"/><section className="px-5">{!logged?<div className="rounded-2xl bg-ink p-6 text-white"><h1 className="text-2xl font-bold">把足迹留在这里</h1><p className="mt-2 text-sm text-white/60">登录后可跨设备同步收藏与路线。</p><button onClick={()=>setLogged(true)} className="mt-5 flex min-h-12 items-center gap-2 rounded-full bg-accent px-6 font-semibold"><LogIn size={18}/>模拟登录</button></div>:<><div className="flex items-center gap-4"><img src={idols[2].avatar} className="h-16 w-16 rounded-full object-cover"/><div><h1 className="text-xl font-bold">循迹旅行者</h1><p className="text-sm text-stone-500">已登录 · 深圳</p></div></div><Block title="我的收藏" icon={<Heart size={19}/>}><MiniPlaces ids={favs}/></Block><Block title="我的路线" icon={<MapPin size={19}/>}><p className="text-sm text-stone-500">当前路线包含 {route.length} 个地点</p><Link to="/route/builder" className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-accent">查看路线 <ChevronRight size={16}/></Link></Block><Block title="关注的爱豆" icon={<Star size={19}/>}>{followedIdols.length?<><div className="flex flex-wrap gap-4">{followedIdols.map(idol=><div key={idol.id} className="w-20 rounded-2xl bg-stone-50 p-2 text-center"><Link to={`/idol/${idol.id}`} title={idol.name} className="block active:scale-95"><span className="mx-auto flex h-12 w-12 items-center justify-center overflow-hidden rounded-full bg-orange-100 text-xs font-bold text-orange-800">{idol.avatar?<img src={idol.avatar} alt="" className="h-full w-full object-cover"/>:idol.name.slice(0,2)}</span><span className="mt-1 block truncate text-[10px] font-semibold">{idol.name}</span></Link><button type="button" onClick={()=>{if(window.confirm(`确定取消关注 ${idol.name} 吗？`))unfollow(idol.id)}} aria-label={`取消关注 ${idol.name}`} className="mt-1 flex min-h-11 w-full items-center justify-center gap-1 text-[10px] text-stone-500 active:text-red-500"><UserMinus size={13}/>取消关注</button></div>)}</div><p className="mt-3 text-[11px] text-stone-400">点击头像查看主页，点击“取消关注”可移除。</p></>:<EmptyState title="还没有关注" body="在首页热门爱豆中点击＋即可关注。"/>}</Block><Block title="投稿与纠错" icon={<MessageSquareWarning size={19}/>}><p className="text-sm text-stone-500">帮助我们补充证据、更新开放信息。</p></Block></>}<Link to="/feedback" className="mt-7 flex min-h-14 w-full items-center gap-3 rounded-2xl bg-white px-4 shadow-soft active:scale-[.99]"><MessageSquareText size={20}/>意见反馈<ChevronRight className="ml-auto" size={18}/></Link><button className="mt-3 flex min-h-14 w-full items-center gap-3 rounded-2xl bg-white px-4"><Settings size={20}/>设置<ChevronRight className="ml-auto" size={18}/></button></section><BottomNav/></main>}
function Block({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-bold">{icon}{title}</h2>{children}</section>}
function MiniPlaces({ids}:{ids:string[]}){const rows=ids.map(id=>places.find(p=>p.id===id)!).filter(Boolean);return rows.length?<div className="space-y-2">{rows.slice(0,3).map(p=><Link to={`/place/${p.id}`} key={p.id} className="block text-sm font-semibold">{p.name}</Link>)}</div>:<EmptyState title="还没有收藏" body="喜欢的地点会出现在这里。"/>}
