import {GripVertical,MoreHorizontal,Plus,Sparkles,Trash2} from 'lucide-react'
import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {BottomNav,Card,EmptyState,Header} from '../components/ui'
import {places as mocks} from '../data/mock'
import {toPublicPlace} from '../data/adminAdapters'
import {useAdminStore,useRouteStore} from '../stores'
import {trackEvent} from '../services/analytics'
export function RouteBuilderPage(){
 const ids=useRouteStore(s=>s.placeIds),remove=useRouteStore(s=>s.remove),reorder=useRouteStore(s=>s.reorder),clear=useRouteStore(s=>s.clear),records=useAdminStore(s=>s.records)
 const[drag,setDrag]=useState<number|null>(null),[duration,setDuration]=useState('半日'),[purposes,setPurposes]=useState(['作品理解']),[sort,setSort]=useState('按距离')
 const all=[...records.filter(x=>x.status==='published').map(toPublicPlace),...mocks],list=ids.map(id=>all.find(x=>x.id===id)).filter(Boolean)
 useEffect(()=>trackEvent({type:'page_view',page:'route_builder',placeCount:list.length}),[])
 const toggle=(x:string)=>setPurposes(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x])
 return <main className="min-h-[100dvh] bg-paper pb-28"><Header title="路线清单" back action={<button className="flex h-11 w-11 items-center justify-center rounded-full bg-white"><MoreHorizontal/></button>}/><section className="px-5"><div className="mb-3 flex items-end justify-between"><div><b>已选地点 · {list.length}</b><p className="mt-1 text-xs text-stone-400">长按可拖动调整顺序</p></div><button onClick={clear} className="min-h-11 text-sm text-stone-500">清空全部</button></div>{!list.length?<EmptyState title="路线还是空的" body="从地点详情页加入想去的地点"/>:<Card className="overflow-hidden">{list.map((p,i)=><div key={p!.id} draggable onDragStart={()=>setDrag(i)} onDragEnd={()=>setDrag(null)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag!==null)reorder(drag,i);setDrag(null)}} className={`grid min-h-24 grid-cols-[28px_64px_1fr_46px] items-center gap-3 border-b px-3 transition last:border-0 ${drag===i?'opacity-50 shadow-xl':''}`}><GripVertical className="text-stone-300"/><img src={p!.images[0]} className="h-16 w-16 rounded-2xl object-cover"/><div><b className="text-sm">{p!.name}</b><p className="mt-1 text-[11px] text-orange-600">公开足迹 · 取景关联</p><p className="text-[11px] text-stone-400">{p!.city||'深圳'} · 城市区域</p></div><div className="text-center"><b className="text-xs">30分钟</b><span className="mx-auto mt-2 flex h-7 w-7 items-center justify-center rounded-full border text-xs">{i+1}</span><button onClick={()=>remove(p!.id)} className="mt-1 text-stone-300"><Trash2 size={14}/></button></div></div>)}</Card>}
 <Block title="出行偏好"><Card className="space-y-5 p-5"><Choice label="出行时长" items={['2小时','半日','一日','多日']} selected={[duration]} click={x=>setDuration(x)}/><Choice label="路线目的" items={['拍照','散步','作品理解','公开同款']} selected={purposes} click={toggle}/><Choice label="排序方式" items={['按距离','按剧情','手动排序']} selected={[sort]} click={x=>setSort(x)}/></Card></Block>
 <Block title="路线预估"><Card className="p-5"><div className="grid grid-cols-3 divide-x text-center"><Stat label="总时长" value={list.length?`${Math.max(2,list.length)}h 30m`:'—'}/><Stat label="总地点数" value={`${list.length} 个`}/><Stat label="适合时间段" value="09:00–14:00"/></div><p className="mt-5 rounded-xl bg-orange-50 p-3 text-center text-xs text-orange-600">✦ 推荐半日慢行路线，适合深度体验与拍照</p></Card></Block>
 <button disabled={list.length<2} onClick={()=>trackEvent({type:'route_generate',placeCount:list.length})} className="mt-6 flex min-h-14 w-full items-center justify-center gap-2 rounded-full bg-gradient-to-r from-orange-300 to-orange-500 font-black text-white disabled:opacity-40"><Sparkles/>生成路线</button><Link to="/" className="mt-3 flex min-h-14 items-center justify-center gap-2 rounded-full bg-white font-bold shadow-soft"><Plus/>继续添加地点</Link></section><BottomNav/></main>
}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-7"><h2 className="mb-3 text-lg font-black">{title}</h2>{children}</section>}
function Choice({label,items,selected,click}:{label:string;items:string[];selected:string[];click:(x:string)=>void}){return <div><b className="text-sm">{label}</b><div className="mt-2 flex gap-2 overflow-x-auto">{items.map(x=><button key={x} onClick={()=>click(x)} className={`min-h-10 shrink-0 rounded-full px-4 text-xs ${selected.includes(x)?'bg-stone-900 text-white':'bg-stone-100'}`}>{x}</button>)}</div></div>}
function Stat({label,value}:{label:string;value:string}){return <div><p className="text-[11px] text-stone-400">{label}</p><b className="mt-2 block text-lg">{value}</b></div>}
