import {Car,Footprints,GripVertical,MapPinned,Plus,RefreshCw,Save,TrainFront,Trash2} from 'lucide-react'
import {useEffect,useMemo,useRef,useState} from 'react'
import {BottomNav,Card,EmptyState,Header} from '../components/ui'
import {places as mocks} from '../data/mock'
import {toPublicPlace} from '../data/adminAdapters'
import {initMap} from '../hooks/useAMap'
import {useAdminStore,useRouteStore} from '../stores'
import {trackEvent} from '../services/analytics'
import type {Place} from '../types'

type TravelMode='walking'|'metro'|'driving'
type Segment={from:Place;to:Place;distance:number;seconds:number;path:[number,number][]}
const modeMeta:Record<TravelMode,{label:string;color:string;soft:string;Icon:typeof Footprints}>={
 walking:{label:'步行',color:'#f97316',soft:'bg-orange-100 text-orange-700',Icon:Footprints},
 metro:{label:'地铁',color:'#4677e8',soft:'bg-blue-100 text-blue-700',Icon:TrainFront},
 driving:{label:'驾车',color:'#d95b42',soft:'bg-rose-100 text-rose-700',Icon:Car}
}

export function RouteBuilderPage(){
 const ids=useRouteStore(s=>s.placeIds),add=useRouteStore(s=>s.add),remove=useRouteStore(s=>s.remove),reorder=useRouteStore(s=>s.reorder),clear=useRouteStore(s=>s.clear),records=useAdminStore(s=>s.records)
 const[drag,setDrag]=useState<number|null>(null),[duration,setDuration]=useState('半日'),[mode,setMode]=useState<TravelMode>('walking'),[showPicker,setShowPicker]=useState(ids.length===0),[planned,setPlanned]=useState(false),[revision,setRevision]=useState(0),[summary,setSummary]=useState({distance:0,seconds:0}),[mapError,setMapError]=useState(''),[saved,setSaved]=useState(false)
 const all=useMemo(()=>Array.from(new Map([...records.filter(x=>x.status==='published').map(toPublicPlace),...mocks].map(place=>[place.id,place])).values()),[records])
 const list=ids.map(id=>all.find(x=>x.id===id)).filter((place):place is Place=>Boolean(place)),available=all.filter(place=>!ids.includes(place.id))
 const tooClose=list.length>=2&&list.every((place,index)=>index===0||distanceKm(list[index-1],place)<0.025)
 useEffect(()=>trackEvent({type:'page_view',page:'route_builder',placeCount:list.length}),[])
 useEffect(()=>{setSaved(false);if(!planned)setSummary({distance:0,seconds:0})},[ids.join('|'),mode])
 const plan=()=>{if(list.length<2||tooClose)return;setPlanned(true);setRevision(value=>value+1);trackEvent({type:'route_generate',placeCount:list.length})}
 const saveRoute=()=>{if(!planned)return;const history=JSON.parse(localStorage.getItem('xunji_saved_routes')||'[]');localStorage.setItem('xunji_saved_routes',JSON.stringify([{id:`route-${Date.now()}`,placeIds:ids,mode,duration,distance:summary.distance,seconds:summary.seconds,createdAt:new Date().toISOString()},...history].slice(0,20)));setSaved(true)}
 return <main className="min-h-[100dvh] bg-paper pb-28"><Header title="路线规划" back action={<span className="flex h-11 min-w-11 items-center justify-center rounded-full bg-white px-3 text-xs font-black"><MapPinned size={17}/><span className="ml-1">{list.length}</span></span>}/><section className="px-4"><div className="mb-3 flex items-center justify-between"><div><b className="text-sm">已选地点 · {list.length}</b><p className="mt-1 text-[11px] text-stone-400">拖动下方地点可实时调整路线顺序</p></div><button onClick={clear} disabled={!list.length} className="min-h-11 text-sm text-stone-500 disabled:opacity-35">清空</button></div>
  <RouteMap places={list} mode={mode} planned={planned} revision={revision} onSummary={setSummary} onError={setMapError}/>
  {mapError&&<p className="mt-3 rounded-2xl bg-amber-50 p-3 text-xs font-semibold leading-5 text-amber-800">{mapError}</p>}
  {list.length<2?<div className="mt-4"><EmptyState title="请至少添加 2 个地点生成路线" body="从下方地点库选择地点后，高德地图会显示标记与出行路径。"/></div>:tooClose?<p className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-800">地点过于集中，请检查坐标后再生成路线。</p>:<RouteSummary summary={summary} mode={mode} planned={planned}/>}
  <Block title="路线地点"><RouteList places={list} drag={drag} onDrag={setDrag} reorder={reorder} remove={remove}/></Block>
  <Block title="出行偏好"><Card className="p-4"><div className="grid grid-cols-3 gap-2">{(Object.keys(modeMeta) as TravelMode[]).map(value=>{const meta=modeMeta[value],Icon=meta.Icon;return <button key={value} onClick={()=>setMode(value)} className={`flex min-h-12 items-center justify-center gap-1.5 rounded-xl text-xs font-black transition ${mode===value?'bg-stone-900 text-white':'bg-stone-100 text-stone-500'}`}><Icon size={16}/>{meta.label}</button>})}</div><p className="mt-3 text-[11px] text-stone-400">步行、驾车使用高德路径规划；地铁以高德底图上的换乘预览线展示，出发前请以高德实时换乘为准。</p></Card></Block>
  <Block title="行程设置"><Card className="p-4"><p className="text-sm font-bold">出行时长</p><div className="mt-3 flex gap-2 overflow-x-auto">{['2小时','半日','一日','多日'].map(value=><button key={value} onClick={()=>setDuration(value)} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-bold ${duration===value?'bg-stone-900 text-white':'bg-stone-100 text-stone-600'}`}>{value}</button>)}</div></Card></Block>
  <div className="mt-6 grid grid-cols-2 gap-3"><button disabled={list.length<2||tooClose} onClick={plan} className="flex min-h-14 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-orange-400 to-orange-600 font-black text-white disabled:opacity-40"><RefreshCw size={18}/>{planned?'重新规划':'生成路线'}</button><button disabled={!planned} onClick={saveRoute} className="flex min-h-14 items-center justify-center gap-2 rounded-full bg-stone-900 font-black text-white disabled:opacity-40"><Save size={18}/>{saved?'已保存':'保存路线'}</button></div>
  <button type="button" onClick={()=>setShowPicker(value=>!value)} className="mt-3 flex min-h-14 w-full items-center justify-center gap-2 rounded-full bg-white font-bold shadow-soft"><Plus className={`transition ${showPicker?'rotate-45':''}`}/>{showPicker?'收起地点选择':'继续添加地点'}</button>{showPicker&&<PlacePicker places={available} add={add}/>}</section><BottomNav/></main>
}

function RouteMap({places,mode,planned,revision,onSummary,onError}:{places:Place[];mode:TravelMode;planned:boolean;revision:number;onSummary:(summary:{distance:number;seconds:number})=>void;onError:(message:string)=>void}){
 const container=useRef<HTMLDivElement>(null)
 useEffect(()=>{let cancelled=false;let map:any;if(!container.current)return;onError('');if(!places.length){container.current.innerHTML='';return}initMap(container.current,{center:[places[0].lng,places[0].lat],zoom:13,resizeEnable:true}).then(async({AMap,map:nextMap})=>{if(cancelled){nextMap.destroy?.();return}map=nextMap;const overlays:any[]=[];const markers=places.map((place,index)=>{const marker=new AMap.Marker({position:[place.lng,place.lat],title:`${index+1}. ${place.name}`,content:markerHtml(place,index+1),offset:new AMap.Pixel(-48,-90),zIndex:150});marker.on('click',()=>new AMap.InfoWindow({offset:new AMap.Pixel(0,-92),content:infoHtml(place,index+1)}).open(map,[place.lng,place.lat]));map.add(marker);return marker});overlays.push(...markers)
   if(places.length>1){const segments:Segment[]=[];for(let index=0;index<places.length-1;index++){const from=places[index],to=places[index+1],segment=planned?await routeSegment(AMap,from,to,mode):fallbackSegment(from,to,mode);if(cancelled)return;segments.push(segment);const polyline=new AMap.Polyline({path:segment.path,strokeColor:modeMeta[mode].color,strokeWeight:6,strokeOpacity:.88,strokeStyle:mode==='metro'?'dashed':'solid',strokeDasharray:mode==='metro'?[12,8]:undefined,lineJoin:'round',zIndex:90});polyline.on('click',(event:any)=>new AMap.InfoWindow({offset:new AMap.Pixel(0,-22),content:`<div style="padding:5px 8px;font-size:12px"><b>${escapeHtml(from.name)} → ${escapeHtml(to.name)}</b><p style="margin:5px 0 0;color:#777">${formatDistance(segment.distance)} · 约 ${formatMinutes(segment.seconds)}</p></div>`}).open(map,event?.lnglat||[from.lng,from.lat]));map.add(polyline);overlays.push(polyline)}onSummary({distance:segments.reduce((total,item)=>total+item.distance,0),seconds:segments.reduce((total,item)=>total+item.seconds,0)})}else onSummary({distance:0,seconds:0});map.setFitView(overlays,false,[42,36,70,36])}).catch(error=>{if(!cancelled)onError(error instanceof Error?`高德地图暂时未加载：${error.message}`:'高德地图暂时未加载，请稍后重试')});return()=>{cancelled=true;map?.destroy?.()}},[places.map(place=>`${place.id}:${place.lng}:${place.lat}`).join('|'),mode,planned,revision])
 return <div className="relative overflow-hidden rounded-[26px] bg-stone-200 shadow-soft"><div ref={container} className="h-[52vh] min-h-[360px] w-full"/><div className="pointer-events-none absolute left-3 top-3 rounded-2xl border border-white/70 bg-white/85 px-3 py-2 text-[11px] font-bold text-stone-700 shadow-sm backdrop-blur"><span className="mr-1.5 inline-block h-2 w-2 rounded-full bg-orange-500"/>高德地图 · {planned?'已规划':'地点预览'}</div></div>
}

function RouteSummary({summary,mode,planned}:{summary:{distance:number;seconds:number};mode:TravelMode;planned:boolean}){const meta=modeMeta[mode],Icon=meta.Icon;return <div className="mt-4 grid grid-cols-[1fr_auto] items-center gap-3 rounded-[22px] bg-stone-900 p-4 text-white"><div><p className="flex items-center gap-1.5 text-xs text-white/70"><Icon size={15}/>{planned?`${meta.label}路线已生成`:'地点连线预览'}</p><b className="mt-1 block text-xl">{formatDistance(summary.distance)} · 约 {formatMinutes(summary.seconds)}</b></div><span className={`rounded-full px-3 py-1.5 text-xs font-black ${meta.soft}`}>{meta.label}</span></div>}
function RouteList({places,drag,onDrag,reorder,remove}:{places:Place[];drag:number|null;onDrag:(index:number|null)=>void;reorder:(from:number,to:number)=>void;remove:(id:string)=>void}){return <Card className="overflow-hidden">{places.map((place,index)=><div key={place.id} draggable onDragStart={()=>onDrag(index)} onDragEnd={()=>onDrag(null)} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(drag!==null)reorder(drag,index);onDrag(null)}} className={`grid min-h-24 grid-cols-[24px_34px_58px_1fr_34px] items-center gap-2 border-b px-3 transition last:border-0 ${drag===index?'opacity-45':''}`}><GripVertical size={17} className="text-stone-300"/><span className="flex h-7 w-7 items-center justify-center rounded-full bg-orange-500 text-xs font-black text-white">{index+1}</span><div className="h-14 w-14 overflow-hidden rounded-xl bg-orange-100">{place.images[0]?<img src={place.images[0]} alt="" className="h-full w-full object-cover"/>:<MapPinned className="m-4 text-orange-500" size={24}/>}</div><div className="min-w-0"><b className="block truncate text-sm">{place.name}</b><p className="mt-1 text-[11px] text-stone-400">停留约 30 分钟 · {place.city||'未填城市'}</p></div><button onClick={()=>remove(place.id)} aria-label={`移除 ${place.name}`} className="flex h-10 w-10 items-center justify-center rounded-full text-stone-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={16}/></button></div>)}</Card>}
async function routeSegment(AMap:any,from:Place,to:Place,mode:TravelMode):Promise<Segment>{if(mode==='metro')return fallbackSegment(from,to,mode);const Service=mode==='driving'?AMap.Driving:AMap.Walking;if(!Service)return fallbackSegment(from,to,mode);try{return await new Promise<Segment>(resolve=>{const service=new Service({hideMarkers:true,showTraffic:false,autoFitView:false});service.search([from.lng,from.lat],[to.lng,to.lat],(status:string,result:any)=>{const route=result?.routes?.[0],rawPath=(route?.steps||[]).flatMap((step:any)=>step.path||[]),path=rawPath.map((point:any):[number,number]=>[Number(point.lng??point.getLng?.()??point[0]),Number(point.lat??point.getLat?.()??point[1])]).filter((point:[number,number])=>Number.isFinite(point[0])&&Number.isFinite(point[1]));if(status==='complete'&&path.length>1)resolve({from,to,path,distance:Number(route.distance)||distanceKm(from,to),seconds:Number(route.time)||estimateSeconds(distanceKm(from,to),mode)});else resolve(fallbackSegment(from,to,mode))})})}catch{return fallbackSegment(from,to,mode)}}
function fallbackSegment(from:Place,to:Place,mode:TravelMode):Segment{const distance=distanceKm(from,to);return{from,to,path:[[from.lng,from.lat],[to.lng,to.lat]],distance,seconds:estimateSeconds(distance,mode)}}
function estimateSeconds(distance:number,mode:TravelMode){const speed=mode==='walking'?4.5:mode==='metro'?25:32;return Math.max(60,Math.round(distance/speed*3600))}
function distanceKm(from:Place,to:Place){if(!Number.isFinite(from.lng)||!Number.isFinite(from.lat)||!Number.isFinite(to.lng)||!Number.isFinite(to.lat))return 0;const radians=(value:number)=>value*Math.PI/180,lat=radians(to.lat-from.lat),lng=radians(to.lng-from.lng),value=Math.sin(lat/2)**2+Math.cos(radians(from.lat))*Math.cos(radians(to.lat))*Math.sin(lng/2)**2;return 6371*2*Math.atan2(Math.sqrt(value),Math.sqrt(1-value))}
function formatDistance(distance:number){return distance>=1?`${distance.toFixed(1)} km`:`${Math.round(distance*1000)} m`}
function formatMinutes(seconds:number){const minutes=Math.max(1,Math.round(seconds/60));return minutes>=60?`${Math.floor(minutes/60)} 小时 ${minutes%60} 分`:`${minutes} 分`}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]||char))}
function markerHtml(place:Place,index:number){const name=escapeHtml(place.name),image=place.images[0]?`<img src="${escapeHtml(place.images[0])}" style="width:44px;height:44px;object-fit:cover;display:block"/>`:`<span style="display:flex;width:44px;height:44px;align-items:center;justify-content:center;background:#ffedd5;color:#ea580c;font-weight:800;font-size:12px">${name.slice(0,2)}</span>`;return `<div style="width:96px;transform:translate(-50%,-100%);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;text-align:center"><div style="position:relative;margin:auto;width:48px;height:48px;overflow:hidden;border:3px solid #fff;border-radius:12px;box-shadow:0 4px 12px rgba(0,0,0,.28)">${image}<span style="position:absolute;left:-7px;top:-8px;display:flex;width:23px;height:23px;align-items:center;justify-content:center;border:2px solid #fff;border-radius:50%;background:#f97316;color:#fff;font-size:12px;font-weight:800">${index}</span></div><span style="display:block;overflow:hidden;margin-top:5px;border-radius:8px;background:rgba(32,28,24,.92);padding:4px 6px;color:#fff;font-size:11px;font-weight:700;text-overflow:ellipsis;white-space:nowrap;box-shadow:0 3px 9px rgba(0,0,0,.18)">${name}</span></div>`}
function infoHtml(place:Place,index:number){const image=place.images[0]?`<img src="${escapeHtml(place.images[0])}" style="width:100%;height:82px;object-fit:cover;border-radius:8px"/>`:'';return `<div style="width:180px;padding:4px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">${image}<b style="display:block;margin-top:7px">${index}. ${escapeHtml(place.name)}</b><p style="margin:5px 0;color:#777;font-size:12px">${escapeHtml(place.city||'')} · 停留约 30 分钟</p></div>`}
type RoutePlace={id:string;name:string;address:string;city?:string;images:string[]}
function PlacePicker({places,add}:{places:RoutePlace[];add:(id:string)=>void}){return <section className="mt-5 rounded-[24px] bg-white p-4 shadow-soft"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-black">选择地点</h2><p className="mt-1 text-[11px] text-stone-400">点击加入，可连续选择多个地点</p></div><span className="rounded-full bg-orange-50 px-3 py-1 text-[11px] text-orange-600">{places.length} 个可选</span></div>{places.length?<div className="max-h-80 space-y-2 overflow-y-auto pr-1">{places.map(place=><div key={place.id} className="grid grid-cols-[56px_1fr_auto] items-center gap-3 rounded-2xl bg-stone-50 p-2"><div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-xl bg-orange-100">{place.images[0]?<img src={place.images[0]} alt="" className="h-full w-full object-cover"/>:<span className="text-xs font-bold text-orange-500">{place.name.slice(0,2)}</span>}</div><div className="min-w-0"><b className="block truncate text-sm">{place.name}</b><p className="mt-1 truncate text-[11px] text-stone-400">{place.city||'深圳'} · {place.address}</p></div><button type="button" onClick={()=>add(place.id)} className="flex min-h-11 items-center gap-1 rounded-full bg-stone-900 px-3 text-xs font-bold text-white"><Plus size={14}/>加入</button></div>)}</div>:<p className="rounded-2xl bg-stone-50 py-8 text-center text-sm text-stone-400">所有可用地点都已加入路线</p>}</section>}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-6"><h2 className="mb-3 text-lg font-black">{title}</h2>{children}</section>}
