import {BookOpen,ChevronRight,Clapperboard,Search,Sparkles,Star} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {BottomNav,Header} from '../components/ui'
import {useAdminStore,useBasicDataStore,type ManagedIdol,type ManagedWork} from '../stores'

type Filter='all'|'movie'|'book'|'animation'|'idol'
type HotItem={id:string;kind:'work'|'idol';name:string;image:string;placeCount:number;subtitle:string;createdAt?:string;year?:number;region?:string;roles?:string[];fanName?:string;cityCount?:number;genre?:string;initial?:string;gender?:string}
const typeNames:Record<string,string>={movie:'电影',tv:'电视剧',variety:'综艺',book:'小说',music:'音乐',other:'动漫'}
const categories=[{key:'movie' as const,title:'电影',Icon:Clapperboard,color:'from-[#ffb14b] to-[#f38b18]'},{key:'book' as const,title:'小说',Icon:BookOpen,color:'from-[#aa83f3] to-[#714acb]'},{key:'animation' as const,title:'动漫',Icon:Sparkles,color:'from-[#f27eb2] to-[#d94389]'},{key:'idol' as const,title:'Idol',Icon:Star,color:'from-[#ffd164] to-[#f39a08]'}]
const categoryMeta:Record<Exclude<Filter,'all'>,{title:string;empty:string}>={movie:{title:'电影',empty:'暂无电影，去后台录入'},book:{title:'小说',empty:'暂无小说，去后台录入'},animation:{title:'动漫',empty:'暂无动漫，去后台录入'},idol:{title:'Idol',empty:'暂无 Idol，去后台录入'}}
const genres=['全部','爱情','动作','悬疑','喜剧','奇幻','科幻','青春','其他']

export function WorksPage(){
 const{works,idols,places}=useContentData(),[query,setQuery]=useState('')
 const match=(name:string)=>name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())
 const idolItems=useMemo(()=>toIdolItems(idols,places).filter(item=>match(item.name)).sort((a,b)=>b.placeCount-a.placeCount),[idols,places,query])
 const workItems=useMemo(()=>toWorkItems(works,places).filter(item=>match(item.name)).sort((a,b)=>b.placeCount-a.placeCount),[works,places,query])
 const placeItems=useMemo(()=>places.filter(place=>match(place.name)||place.relatedIdols.some(match)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,3),[places,query])
 return <main className="min-h-[100dvh] bg-[radial-gradient(circle_at_top_left,#ffead0_0,transparent_38%),#FAF8F5] pb-28">
  <header className="px-5 pt-9"><p className="flex items-center gap-2 text-xs font-bold text-orange-500"><span className="h-2 w-2 rounded-full bg-orange-400"/>探索与发现</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">作品与 Idol</h1><label className="mt-6 flex min-h-14 items-center gap-3 rounded-[20px] bg-white px-4 shadow-soft"><Search size={19} className="text-stone-400"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索作品或 Idol" className="w-full bg-transparent text-sm outline-none"/></label></header>
  <section className="mt-7 px-5"><h2 className="mb-4 text-sm font-black">选择类型</h2><div className="grid grid-cols-2 gap-3">{categories.map(({key,title,Icon,color})=>{const entries=key==='idol'?idolItems:workItems.filter(item=>key==='animation'?item.genre==='其他'&&works.find(work=>work.id===item.id)?.type==='other':works.find(work=>work.id===item.id)?.type===key);return <TypeCard key={key} to={`/works/${key}`} title={title} count={entries.length} Icon={Icon} color={color} preview={key==='idol'?entries.slice(0,3):entries[0]}/>} )}</div></section>
  <ContentHeader title="热门 Idol" to="/works/idol"/><section className="px-5"><div className="flex gap-4 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{idolItems.slice(0,8).map(item=><Link to={`/idol/${item.id}`} key={item.id} className="w-[82px] shrink-0 text-center"><Avatar item={item} className="mx-auto h-16 w-16 border-2 border-orange-200 shadow-sm"/><b className="mt-2 block truncate text-xs">{item.name}</b><p className="mt-1 text-[10px] text-stone-400">{item.placeCount} 个地点</p></Link>)}{!idolItems.length&&<SmallEmpty text="暂无 Idol"/>}</div></section>
  <ContentHeader title="热门作品" to="/works/movie"/><section className="grid grid-cols-2 gap-3 px-5">{workItems.slice(0,4).map(item=><HomeWorkCard key={item.id} item={item}/>)}{!workItems.length&&<SmallEmpty text="暂无作品"/>}</section>
  <ContentHeader title="热门同款地点" to="/map"/><section className="space-y-3 px-5">{placeItems.map(place=><Link to={`/place/${place.id}`} key={place.id} className="grid grid-cols-[80px_1fr] gap-3 rounded-[20px] bg-white p-3 shadow-soft active:scale-[.99]"><div className="h-20 overflow-hidden rounded-2xl bg-emerald-100">{place.images[0]?<img loading="lazy" src={place.images[0]} alt={place.name} className="h-full w-full object-cover"/>:<span className="flex h-full items-center justify-center text-xs font-bold text-emerald-700">{place.name.slice(0,2)}</span>}</div><div className="min-w-0"><b className="block truncate text-sm">{place.name}</b><p className="mt-1 truncate text-[11px] text-stone-400">{place.city} · {place.address}</p><div className="mt-2 flex gap-1 overflow-hidden">{place.relatedIdols.slice(0,2).map(name=><span key={name} className="truncate rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700">{name}</span>)}</div></div></Link>)}{!placeItems.length&&<SmallEmpty text="暂无已发布地点"/>}</section><BottomNav/>
 </main>
}

function TypeCard({to,title,count,Icon,color,preview}:{to:string;title:string;count:number;Icon:typeof Star;color:string;preview?:HotItem|HotItem[]}){const inactive=count===0,previews=Array.isArray(preview)?preview:preview?[preview]:[],first=previews[0];return <Link to={to} className={`relative min-h-28 overflow-hidden rounded-[22px] p-4 shadow-soft transition active:scale-[.97] ${inactive?'bg-stone-200 text-stone-500 opacity-65':`bg-gradient-to-br ${color} text-white`}`}><Icon size={25}/><b className="mt-2 block text-base">{title}</b><p className="mt-1 text-xs opacity-80">{count} {title==='Idol'?'位':'部'}</p>{first&&<div className="absolute bottom-2 right-2">{title==='Idol'?<div className="flex -space-x-3">{previews.slice(0,3).map(item=><Avatar key={item.id} item={item} className="h-9 w-9 border-2 border-white"/>)}</div>:<div className="h-14 w-10 overflow-hidden rounded-lg border-2 border-white/70 bg-white/25">{first.image?<img src={first.image} alt="" className="h-full w-full object-cover"/>:<span className="flex h-full items-center justify-center text-[9px] font-bold">{first.name.slice(0,2)}</span>}</div>}</div>}</Link>}
function ContentHeader({title,to}:{title:string;to:string}){return <div className="mt-8 flex items-center justify-between px-5"><h2 className="text-lg font-black">{title}</h2><Link to={to} className="min-h-10 py-2 text-xs font-bold text-orange-500">全部 ›</Link></div>}
function Avatar({item,className}:{item:HotItem;className:string}){const[broken,setBroken]=useState(false);return <span className={`relative flex shrink-0 items-center justify-center overflow-hidden rounded-full bg-gradient-to-br from-orange-200 via-rose-100 to-amber-100 text-sm font-black text-orange-700 ${className}`}><span>{item.name.slice(0,2)}</span>{item.image&&!broken&&<img loading="lazy" src={item.image} alt={item.name} onError={()=>setBroken(true)} className="absolute inset-0 h-full w-full object-cover"/>}</span>}
function HomeWorkCard({item}:{item:HotItem}){const[broken,setBroken]=useState(false);return <Link to={`/work/${item.id}`} className="group overflow-hidden rounded-[20px] bg-white shadow-soft active:scale-[.98]"><div className="relative aspect-[3/4] overflow-hidden bg-gradient-to-br from-violet-200 to-sky-100">{item.image&&!broken?<img loading="lazy" src={item.image} alt={item.name} onError={()=>setBroken(true)} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<span className="flex h-full items-center justify-center p-4 text-center text-sm font-black text-violet-700">{item.name}</span>}<span className="absolute left-2 top-2 rounded-full bg-slate-950/65 px-2 py-1 text-[10px] font-bold text-white">{item.subtitle.split(' · ')[0]}</span></div><div className="p-3"><b className="block truncate text-sm">{item.name}</b><p className="mt-1 text-[11px] text-stone-400">{item.placeCount} 个地点 · {item.year||'待补充'}</p></div></Link>}
function SmallEmpty({text}:{text:string}){return <p className="w-full rounded-2xl bg-white px-4 py-6 text-center text-sm text-stone-400 shadow-soft">{text}</p>}

export function WorkCategoryPage(){
 const{category}=useParams(),key=(category==='movie'||category==='book'||category==='animation'||category==='idol'?category:'movie') as Exclude<Filter,'all'>
 const{works,idols,places}=useContentData(),[query,setQuery]=useState(''),[genre,setGenre]=useState('全部'),[year,setYear]=useState('全部'),[region,setRegion]=useState('全部'),[role,setRole]=useState('全部'),[gender,setGender]=useState('全部'),[initial,setInitial]=useState('全部'),[sort,setSort]=useState('关联地点数'),[limit,setLimit]=useState(12)
 const allItems=useMemo(()=>key==='idol'?toIdolItems(idols,places):toWorkItems(works.filter(work=>key==='movie'?work.type==='movie':key==='book'?work.type==='book':work.type==='other'),places),[key,works,idols,places])
 const regions=useMemo(()=>['全部',...new Set(['中国大陆','中国香港','韩国','日本',...allItems.map(item=>item.region).filter((value):value is string=>Boolean(value)&&value!=='地区待补充')])],[allItems])
 const roles=useMemo(()=>['全部',...new Set(['演员','歌手','偶像','主持人',...allItems.flatMap(item=>item.roles||[])])],[allItems])
 const filtered=useMemo(()=>allItems.filter(item=>{if(!item.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))return false;if(key==='idol')return (role==='全部'||item.roles?.includes(role))&&(gender==='全部'||item.gender===gender)&&(initial==='全部'||item.initial===initial);const yearMatch=year==='全部'||(year==='更早'?(item.year||0)<2022:item.year===Number(year));return (genre==='全部'||item.genre===genre)&&yearMatch&&(region==='全部'||item.region===region)}).sort((a,b)=>sort==='最新录入'?String(b.createdAt||'').localeCompare(String(a.createdAt||'')):sort==='首字母'?a.name.localeCompare(b.name,'zh-CN'):b.placeCount-a.placeCount||a.name.localeCompare(b.name,'zh-CN')),[allItems,key,query,genre,year,region,role,gender,initial,sort])
 useEffect(()=>setLimit(12),[key,query,genre,year,region,role,gender,initial,sort])
 const meta=categoryMeta[key],isIdol=key==='idol',shown=filtered.slice(0,limit)
 return <main className="min-h-[100dvh] bg-[radial-gradient(circle_at_top_left,#ffead0_0,transparent_38%),#FAF8F5] pb-28"><Header title={meta.title} back/><section className="px-5 pt-3"><label className="flex min-h-12 items-center gap-3 rounded-2xl bg-white px-4 shadow-soft"><Search size={18} className="text-stone-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder={`搜索${meta.title}`}/></label><div className="mt-4 rounded-[20px] bg-white p-4 shadow-soft"><p className="text-sm font-black">筛选与排序</p>{isIdol?<><FilterRow label="身份" values={roles} selected={role} onChange={setRole}/><FilterRow label="类别" values={['全部','男','女','组合','未知']} selected={gender} onChange={setGender}/><FilterRow label="首字母" values={['全部',...'ABCDEFGHIJKLMNOPQRSTUVWXYZ','中']} selected={initial} onChange={setInitial}/><p className="mt-2 text-[10px] text-stone-400">中文姓名暂归入“中”；补充拼音后可进一步细分首字母。</p></>:<><FilterRow label="题材" values={genres} selected={genre} onChange={setGenre}/><FilterRow label="年份" values={['全部','2024','2023','2022','更早']} selected={year} onChange={setYear}/><FilterRow label="地区" values={regions} selected={region} onChange={setRegion}/></>}<FilterRow label="排序" values={['关联地点数','最新录入','首字母']} selected={sort} onChange={setSort}/></div><div className="mt-5 flex items-center justify-between"><div><h2 className="text-lg font-black">全部{meta.title}</h2><p className="mt-1 text-xs text-stone-400">{filtered.length} 条结果 · 点击查看详情</p></div><span className="rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-600">{sort}</span></div>{!allItems.length?<EmptyCategory title={meta.empty}/>:!filtered.length?<EmptyCategory title="没有符合条件的内容，换个筛选条件试试"/>:<><div className="mt-4 grid grid-cols-2 gap-3 min-[720px]:grid-cols-3">{shown.map(item=>isIdol?<IdolGridCard key={item.id} item={item}/>:<WorkGridCard key={item.id} item={item}/>)}</div>{limit<filtered.length&&<button onClick={()=>setLimit(value=>value+12)} className="mt-5 flex min-h-12 w-full items-center justify-center rounded-2xl bg-white text-sm font-black text-orange-600 shadow-soft">加载更多（剩余 {filtered.length-limit}）</button>}</>}</section><BottomNav/></main>
}

function useContentData(){const works=useBasicDataStore(s=>s.works).filter((work):work is ManagedWork=>Boolean(work)&&typeof work.name==='string'),idols=useBasicDataStore(s=>s.idols).filter((idol):idol is ManagedIdol=>Boolean(idol)&&typeof idol.name==='string'),places=useAdminStore(s=>s.records).filter(place=>place.status==='published');return{works,idols,places}}
function toWorkItems(works:ManagedWork[],places:ReturnType<typeof useAdminStore.getState>['records']):HotItem[]{return works.map(work=>{const placeCount=places.filter(place=>(place.relatedWorkIds||[]).includes(work.id)||[...place.relatedMovies,...place.relatedTV,...place.relatedVariety,...(place.relatedOtherWorks||[])].includes(work.name)).length;return{id:work.id,kind:'work',name:work.name,image:work.cover,placeCount,subtitle:`${typeNames[work.type]||'作品'} · ${placeCount} 个地点`,createdAt:work.createdAt,year:work.year,region:work.region||'地区待补充',genre:workGenre(work)}})}
function toIdolItems(idols:ManagedIdol[],places:ReturnType<typeof useAdminStore.getState>['records']):HotItem[]{return idols.map(idol=>{const placeCount=places.filter(place=>(place.relatedIdolIds||[]).includes(idol.id)||(place.relatedIdolNames||place.relatedIdols).includes(idol.name)).length,cityCount=new Set([...(idol.cityNames||[]),...places.filter(place=>(place.relatedIdolIds||[]).includes(idol.id)||(place.relatedIdolNames||place.relatedIdols).includes(idol.name)).map(place=>place.city)]).size;return{id:idol.id,kind:'idol',name:idol.name,image:idol.avatar,placeCount,subtitle:`Idol · ${cityCount} 个城市 · ${placeCount} 个公开地点`,createdAt:idol.createdAt,roles:idol.roles,fanName:idol.fanName,cityCount,initial:initialOf(idol.name),gender:genderOf(idol)}})}
function workGenre(work:ManagedWork){const text=`${work.name} ${work.quote}`;return genres.slice(1,-1).find(genre=>text.includes(genre))||'其他'}
function genderOf(idol:ManagedIdol){const text=`${idol.name} ${(idol.roles||[]).join(' ')}`;return /组合|团体|group/i.test(text)?'组合':/男|先生|男团/.test(text)?'男':/女|小姐|女团/.test(text)?'女':'未知'}
function initialOf(name:string){const first=name.trim().charAt(0).toUpperCase();return /^[A-Z]$/.test(first)?first:'中'}
function FilterRow({label,values,selected,onChange}:{label:string;values:string[];selected:string;onChange:(value:string)=>void}){return <div className="mt-3"><p className="mb-2 text-[11px] font-bold text-stone-400">{label}</p><div className="flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{values.map(value=><button key={value} onClick={()=>onChange(value)} className={`min-h-9 shrink-0 rounded-full px-3 text-xs font-semibold ${selected===value?'bg-stone-900 text-white':'bg-stone-100 text-stone-600'}`}>{value}</button>)}</div></div>}
function WorkGridCard({item}:{item:HotItem}){return <Link to={`/work/${item.id}`} className="group overflow-hidden rounded-[20px] bg-white shadow-soft transition active:scale-[.98]"><div className="aspect-[3/4] overflow-hidden bg-gradient-to-br from-orange-100 to-stone-100">{item.image?<img loading="lazy" src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="flex h-full items-center justify-center p-4 text-center text-sm font-black text-stone-500">{item.name}</div>}</div><div className="p-3"><b className="block truncate text-sm">{item.name}</b><p className="mt-1 truncate text-[11px] text-stone-400">{item.year||'年份待补充'} · {item.genre}</p><div className="mt-2 flex items-center justify-between"><span className="rounded-full bg-orange-50 px-2 py-1 text-[10px] font-bold text-orange-600">{item.placeCount} 个地点</span><span className="text-[10px] text-stone-400">{item.region||'—'}</span></div></div></Link>}
function IdolGridCard({item}:{item:HotItem}){return <Link to={`/idol/${item.id}`} className="group rounded-[20px] bg-white p-4 text-center shadow-soft transition active:scale-[.98]"><div className="mx-auto flex aspect-square w-full max-w-28 items-center justify-center overflow-hidden rounded-full bg-gradient-to-br from-orange-100 to-amber-50 text-xl font-black text-orange-600">{item.image?<img loading="lazy" src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:item.name.slice(0,2)}</div><b className="mt-3 block truncate text-sm">{item.name}</b><p className="mt-1 truncate text-[11px] text-stone-400">{item.roles?.join(' · ')||'资料待补充'}</p><p className="mt-2 text-[10px] text-orange-600">{item.cityCount||0} 城市 · {item.placeCount} 地点</p>{item.fanName&&<span className="mt-2 inline-block rounded-full bg-orange-50 px-2 py-1 text-[10px] text-orange-700">{item.fanName}</span>}</Link>}
function EmptyCategory({title}:{title:string}){return <div className="mt-5 rounded-[22px] border border-dashed border-stone-300 bg-white px-5 py-14 text-center"><p className="font-bold text-stone-600">{title}</p><Link to="/admin/work" className="mt-3 inline-flex text-sm font-bold text-orange-600">去后台录入 →</Link></div>}
function ContentRows({items,empty='没有符合条件的内容'}:{items:HotItem[];empty?:string}){return <div className="space-y-3">{items.map(item=><Link to={item.kind==='work'?`/work/${item.id}`:`/idol/${item.id}`} key={`${item.kind}-${item.id}`} className="grid min-h-20 grid-cols-[52px_1fr_20px] items-center gap-3 rounded-[20px] bg-white p-3 shadow-soft transition active:scale-[.98]">{item.image?<img loading="lazy" src={item.image} className={`h-12 w-12 object-cover ${item.kind==='idol'?'rounded-full':'rounded-xl'}`} alt={item.name}/>:<span className="flex h-12 w-12 items-center justify-center rounded-xl bg-orange-50 text-orange-500">{item.kind==='idol'?<Star/>:<Clapperboard/>}</span>}<div><b>{item.name}</b><p className="mt-1 text-xs text-stone-400">{item.subtitle}</p></div><ChevronRight size={18} className="text-stone-400"/></Link>)}{!items.length&&<div className="rounded-[22px] border border-dashed border-stone-300 py-14 text-center text-sm text-stone-400">{empty}</div>}</div>}
