import {Bookmark,ChevronLeft,Clapperboard,Home,Map,MapPinned,Route,Search,UserRound} from 'lucide-react'
import {NavLink,useNavigate} from 'react-router-dom'
import {useEffect,useState} from 'react'
import type {Credibility,RelationType} from '../types'
const meta:Record<Credibility,[string,string]>={A:['可打卡 A','bg-emerald-100 text-emerald-700'],B:['可打卡 B','bg-blue-100 text-blue-700'],C:['待核验 C','bg-orange-100 text-orange-700'],D:['氛围 D','bg-stone-200 text-stone-600']}
export function haptic(duration=8){if(typeof navigator!=='undefined'&&'vibrate' in navigator)navigator.vibrate(duration)}
export function CredibilityBadge({level}:{level:Credibility}){return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold ${meta[level][1]}`}>{meta[level][0]}</span>}
export const relationLabel:Record<RelationType,string>={same_style:'公开同款',filming:'取景地',public_event:'公开活动',personal_share:'本人分享',other:'氛围关联'}
export function Header({title,back=false,action}:{title:string;back?:boolean;action?:React.ReactNode}){const nav=useNavigate();const[scrolled,setScrolled]=useState(false);useEffect(()=>{const sync=()=>setScrolled(window.scrollY>8);sync();window.addEventListener('scroll',sync,{passive:true});return()=>window.removeEventListener('scroll',sync)},[]);return <header data-scrolled={scrolled} className="xj-glass xj-glass-nav sticky top-0 z-30 flex h-16 items-center justify-between px-5"><button aria-label="返回" onClick={()=>back&&nav(-1)} className={`xj-press flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-soft ${back?'':'invisible'}`}><ChevronLeft strokeWidth={1.75}/></button><h1 className="xj-title font-bold">{title}</h1><div className="flex h-11 min-w-11 items-center justify-end">{action||<span/>}</div></header>}
export function BottomNav(){const items=[['/','首页',Home],['/works','作品',Clapperboard],['/map','地图',MapPinned],['/route/builder','路线',Route],['/profile','我的',UserRound]] as const;return <nav className="xj-tabbar fixed bottom-[max(.65rem,env(safe-area-inset-bottom))] left-1/2 z-40 grid w-[calc(100%-1rem)] -translate-x-1/2 grid-cols-5 rounded-[24px] px-2 py-2 md:w-[414px] md:max-w-[calc(100%-3rem)]">{items.map(([to,label,Icon])=><NavLink key={`${to}-${label}`} to={to} end={to==='/'} onClick={()=>haptic()} className={({isActive})=>`xj-press flex min-h-12 flex-col items-center justify-center gap-1 text-[10px] font-medium ${isActive?'text-[var(--xj-accent)]':'text-stone-400'}`}><span className="flex h-7 items-center justify-center"><Icon size={22} strokeWidth={1.75}/></span>{label}</NavLink>)}</nav>}
export function EmptyState({title,body}:{title:string;body:string}){return <div className="rounded-3xl border border-dashed border-stone-300 p-8 text-center"><Map className="mx-auto mb-3 text-stone-400"/><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-stone-500">{body}</p></div>}
export function SearchBox({value='',onChange,onClick,autoFocus=false,placeholder='搜索 Idol / 作品 / 地点 / 城市'}:{value?:string;onChange?:(v:string)=>void;onClick?:()=>void;autoFocus?:boolean;placeholder?:string}){return <label className="xj-search flex min-h-14 items-center gap-3 rounded-[22px] px-4"><Search size={20} strokeWidth={1.75} className="text-stone-400"/><input autoFocus={autoFocus} value={value} onChange={e=>onChange?.(e.target.value)} onFocus={onClick} placeholder={placeholder} className="w-full bg-transparent text-sm outline-none"/></label>}
export function PageAction({active=false,onClick}:{active?:boolean;onClick?:()=>void}){return <button onClick={()=>{haptic();onClick?.()}} className={`xj-press flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-soft ${active?'text-[var(--xj-accent)]':'text-stone-700'}`}><Bookmark size={20} strokeWidth={1.75} fill={active?'currentColor':'none'}/></button>}
export function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={`xj-panel ${className}`}>{children}</div>}
export {Bookmark,Map,Route}
