import {BookOpen,Bookmark,ChevronLeft,Home,Map,MapPinned,Route,Search,UserRound} from 'lucide-react'
import {NavLink,useNavigate} from 'react-router-dom'
import type {Credibility,RelationType} from '../types'
const meta:Record<Credibility,[string,string]>={A:['可打卡 A','bg-emerald-100 text-emerald-700'],B:['可打卡 B','bg-blue-100 text-blue-700'],C:['待核验 C','bg-orange-100 text-orange-700'],D:['氛围 D','bg-stone-200 text-stone-600']}
export function CredibilityBadge({level}:{level:Credibility}){return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold ${meta[level][1]}`}>{meta[level][0]}</span>}
export const relationLabel:Record<RelationType,string>={same_style:'公开同款',filming:'取景地',public_event:'公开活动',personal_share:'本人分享',other:'氛围关联'}
export function Header({title,back=false,action}:{title:string;back?:boolean;action?:React.ReactNode}){const nav=useNavigate();return <header className="sticky top-0 z-30 flex h-16 items-center justify-between bg-paper/90 px-5 backdrop-blur-xl"><button aria-label="返回" onClick={()=>back&&nav(-1)} className={`flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-soft active:scale-95 ${back?'':'invisible'}`}><ChevronLeft/></button><h1 className="font-black tracking-wide">{title}</h1><div className="flex h-11 min-w-11 items-center justify-end">{action||<span/>}</div></header>}
export function BottomNav(){const items=[['/','首页',Home],['/works','作品',BookOpen],['/map','地图',MapPinned],['/route/builder','路线',Route],['/profile','我的',UserRound]] as const;return <nav className="fixed bottom-0 left-1/2 z-40 grid w-full max-w-md -translate-x-1/2 grid-cols-5 rounded-t-[28px] border-t border-white/80 bg-white/95 px-2 pb-[max(.55rem,env(safe-area-inset-bottom))] pt-2 shadow-[0_-12px_35px_rgba(70,50,30,.08)] backdrop-blur-xl">{items.map(([to,label,Icon],i)=><NavLink key={`${to}-${label}`} to={to} end={to==='/'} className={({isActive})=>`flex min-h-12 flex-col items-center justify-center gap-1 text-[10px] transition active:scale-95 ${isActive?'text-[#f2a91d]':'text-stone-400'} ${i===2?'relative -top-3':''}`}><span className={i===2?'flex h-11 w-11 items-center justify-center rounded-full bg-[#1f1f1f] text-white shadow-lg':''}><Icon size={20}/></span>{label}</NavLink>)}</nav>}
export function EmptyState({title,body}:{title:string;body:string}){return <div className="rounded-3xl border border-dashed border-stone-300 p-8 text-center"><Map className="mx-auto mb-3 text-stone-400"/><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-stone-500">{body}</p></div>}
export function SearchBox({value='',onChange,onClick,autoFocus=false,placeholder='搜索 Idol / 作品 / 地点 / 城市'}:{value?:string;onChange?:(v:string)=>void;onClick?:()=>void;autoFocus?:boolean;placeholder?:string}){return <label className="flex min-h-14 items-center gap-3 rounded-[20px] bg-white px-4 shadow-soft"><Search size={20} className="text-stone-400"/><input autoFocus={autoFocus} value={value} onChange={e=>onChange?.(e.target.value)} onFocus={onClick} placeholder={placeholder} className="w-full bg-transparent text-sm outline-none"/></label>}
export function PageAction({active=false,onClick}:{active?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={`flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-soft active:scale-95 ${active?'text-orange-500':'text-stone-700'}`}><Bookmark size={20} fill={active?'currentColor':'none'}/></button>}
export function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={`rounded-[24px] bg-white shadow-soft ${className}`}>{children}</div>}
export {Bookmark,Map,Route}
